#!/usr/bin/env python3
"""Atlas: how much of the graph do the sense collisions actually reach?
(#ATLAS-AMBIG)

WHY
---
`atlas_ambiguity.py` measures which surface forms collide, and `resolve` now
refuses to guess on them. Neither answers the question a reader of this graph
actually has: **how much of it should I discount?**

The obvious way to answer it is wrong, and wrong by a factor of about forty.
Counting relation rows that touch a contested identifier gives about half, which
sounds catastrophic and measures almost nothing. `ESR1` is a contested
identifier because the string `ER` is ambiguous -- but the overwhelming majority
of ESR1 edges come from papers that wrote "estrogen receptor" in full, where
nothing was ever ambiguous. That figure measures CONTAINMENT (how much of the
graph involves entities that are ambiguous *somewhere*), not error.

The measurement that means something asks, per paper and per identifier, whether
the ambiguous surface form was the ONLY route to that assignment. If a paper
writes both "ER" and "estrogen receptor", the assignment is corroborated and the
collision cost nothing. If it only ever writes "ER", the assignment rests
entirely on a majority vote that this project has measured to be wrong four
times in five.

WHAT IT FINDS
-------------
A small fraction of relation rows rest on an uncorroborated ambiguous assignment. That is
the honest upper bound on the damage, and it is an upper bound rather than an
estimate because the vote is sometimes right (`PSA` resolves to KLK3 correctly).

Both numbers are reported together, because reporting either alone misleads: the
first overstates by ~40x, and the second alone hides how widely ambiguity is
distributed.

Reads only committed artifacts plus the gitignored entity/relation dumps. No
network.

Usage:
    python scripts/atlas_ambiguity_impact.py
"""

import collections
import gzip
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_baseline import atlas_root  # noqa: E402
from config import PROJECT_ROOT  # noqa: E402

SCAN = PROJECT_ROOT / "analysis" / "atlas-ambiguity.json"
OUT = PROJECT_ROOT / "analysis" / "atlas-ambiguity-impact.md"
RAW = PROJECT_ROOT / "analysis" / "atlas-ambiguity-impact.json"


def main() -> int:
    try:
        scan = json.loads(SCAN.read_text())
    except (OSError, ValueError):
        print(f"missing {SCAN}; run scripts/atlas_ambiguity.py first", file=sys.stderr)
        return 1

    blocked = set(scan["blocklist"])
    contested = set()
    for t in ("gene", "chemical", "disease"):
        for r in scan["by_type"][t]["sense_rows"]:
            contested |= {r["top"]["id"], r["runner_up"]["id"]}
    print(f"{len(blocked)} blocked forms over {len(contested)} identifiers", flush=True)

    root = atlas_root()
    # For each (paper, contested identifier): was it reached via an ambiguous
    # surface form, via an unambiguous one, or both?
    via_ambiguous, via_clear = set(), set()
    for kind in ("gene", "chemical", "disease"):
        f = root / "entities" / f"{kind}.tsv.gz"
        if not f.exists():
            continue
        print(f"  reading {kind} ...", flush=True)
        with gzip.open(f, "rt", errors="replace") as fh:
            for line in fh:
                p = line.rstrip("\n").split("\t")
                if len(p) < 4 or p[2] not in contested:
                    continue
                key = (p[0], p[2])
                forms = [s.strip().lower() for s in p[3].split("|")]
                if any(s in blocked for s in forms):
                    via_ambiguous.add(key)
                if any(s not in blocked for s in forms):
                    via_clear.add(key)

    all_keys = via_ambiguous | via_clear
    corroborated = via_ambiguous & via_clear
    at_risk = via_ambiguous - via_clear
    unaffected = via_clear - via_ambiguous

    print("  reading relations ...", flush=True)
    rows = touching = resting = 0
    with gzip.open(root / "relations" / "relations.tsv.gz", "rt", errors="replace") as fh:
        for line in fh:
            p = line.rstrip("\n").split("\t")
            if len(p) < 4:
                continue
            rows += 1
            a = p[2].split("|", 1)[-1]
            b = p[3].split("|", 1)[-1]
            if a in contested or b in contested:
                touching += 1
            if (p[0], a) in at_risk or (p[0], b) in at_risk:
                resting += 1

    pct = lambda n, d: 100 * n / d if d else 0.0  # noqa: E731
    L = [
        "# How far do the sense collisions actually reach? (#ATLAS-AMBIG)", "",
        "Generated by `scripts/atlas_ambiguity_impact.py`. The ambiguity scan says",
        "which surface forms collide. This says how much of the graph to discount,",
        "which is a different question with a very different answer.", "",
        "## The number not to use", "",
        f"**{pct(touching, rows):.1f}%** of relation rows touch an identifier that is",
        "contested somewhere in the census. That sounds severe and means almost",
        "nothing. `ESR1` is contested because the string `ER` is ambiguous, but most",
        "ESR1 edges come from papers that wrote *estrogen receptor* in full, where",
        "nothing was ever in doubt. This measures how widely ambiguity is",
        "distributed, not how often it caused an error.", "",
        "## The number that means something", "",
        "Per paper and per identifier: was an ambiguous surface form the **only**",
        "route to that assignment? A paper writing both `ER` and *estrogen receptor*",
        "corroborates itself and the collision cost nothing. A paper writing only",
        "`ER` rests entirely on the majority vote.", "",
        "| | assignments | share |", "|---|---|---|",
        f"| reached only by an unambiguous mention | {len(unaffected):,} | "
        f"{pct(len(unaffected), len(all_keys)):.1f}% |",
        f"| reached by both, so corroborated | {len(corroborated):,} | "
        f"{pct(len(corroborated), len(all_keys)):.1f}% |",
        f"| **at risk** -- ambiguous form the only route | **{len(at_risk):,}** | "
        f"**{pct(len(at_risk), len(all_keys)):.1f}%** |",
        f"| total involving a contested identifier | {len(all_keys):,} | |", "",
        f"Of the {len(via_ambiguous):,} assignments that involve an ambiguous form at",
        f"all, {pct(len(at_risk), len(via_ambiguous)):.0f}% have no corroborating",
        "unambiguous mention.", "",
        f"**{pct(resting, rows):.2f}%** of the {rows:,} relation rows rest on an",
        f"at-risk assignment -- {resting:,} rows.", "",
        f"That is roughly {pct(touching, rows)/max(pct(resting, rows), 1e-9):.0f}x",
        "smaller than the containment figure above, which is why both are reported",
        "here and neither is reported alone.", "",
        "## It is an upper bound, not an estimate", "",
        "An at-risk assignment is one the majority vote decided unaided. It is not",
        "necessarily wrong: for `PSA` the vote already returns KLK3, the correct",
        "gene, and the form is blocklisted only because NPEPPS is a genuinely",
        "different gene (`analysis/atlas-domain-sense-validation.md`). So the true",
        "error rate is below this bound by an unmeasured amount.", "",
        "What can be said with confidence is the direction: where the vote IS wrong,",
        "it is wrong consistently, picking the sense the cancer literature never",
        "means. Four of the five curated collisions are wrong that way.", "",
        "## What follows for a reader", "",
        "* The graph is not 50% corrupt, and it is not clean either.",
        "* Aggregate counts over the whole graph are affected at the ~1% level, which",
        "  is below the extractor's own ~79.6 F1 error and should not change any",
        "  conclusion drawn from them.",
        "* A query about a SPECIFIC ambiguous entity is a different matter entirely:",
        "  there the error rate is not 1% but can approach 100%, as it did for",
        "  GPX4-FSP1, which had zero correct typed relations before the fix. That",
        "  asymmetry -- diffuse damage small, targeted damage total -- is the",
        "  practical lesson.", "",
        "## Limits", "",
        "* 'Unambiguous mention' means a surface form not on the blocklist, and the",
        "  blocklist covers only the top forms per entity type that could be resolved",
        "  against NCBI and NLM. A collision in the unmeasured tail counts here as",
        "  corroboration, so the at-risk figure is understated to that extent.",
        "* Corroboration is evidence, not proof: a paper can write both `ER` and",
        "  *estrogen receptor* and still have had the short form attached to the",
        "  wrong edge.",
        "* Relation rows are counted, not weighted by how much any analysis relies on",
        "  them. A single wrong edge under a headline claim matters more than a",
        "  thousand in a corner nobody queries.",
    ]
    OUT.write_text("\n".join(L) + "\n")
    RAW.write_text(json.dumps({
        "blocked_forms": len(blocked), "contested_identifiers": len(contested),
        "assignments_total": len(all_keys),
        "assignments_unaffected": len(unaffected),
        "assignments_corroborated": len(corroborated),
        "assignments_at_risk": len(at_risk),
        "relation_rows": rows,
        "relation_rows_touching_contested_id": touching,
        "relation_rows_resting_on_at_risk": resting,
    }, indent=2) + "\n")
    print(f"\ncontainment {pct(touching, rows):.1f}%  ->  at-risk {pct(resting, rows):.2f}%")
    print(f"wrote {OUT}\nwrote {RAW}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
