#!/usr/bin/env python3
"""Atlas: audit gene-name resolution against NCBI's canonical symbols (#ATLAS).

WHY
---
A literature knowledge graph is only as good as its entity resolution, and
biomedical gene symbols collide badly. This was found the hard way: PubTator3
maps 357 mentions of `FSP1` and 90 of `ferroptosis suppressor protein 1` to
NCBI Gene **51062**, which is **ATL1 (atlastin GTPase 1)** -- a hereditary
spastic paraplegia gene with nothing to do with ferroptosis. The real FSP1 is
**84883 (AIFM2, "AIF family member 2, ferroptosis suppressor")**.

That single collision sits directly under the manuscript's headline GPX4+FSP1
Bliss-synergy claim. Querying the graph for FSP1 returns ATL1's edges.

So before any analysis is built on this graph, the symbols it will be queried
with have to be checked against NCBI's own record. This script does that: for a
list of symbols, it reports which identifier PubTator assigns, what NCBI calls
that identifier, and flags every mismatch.

Requires network (NCBI E-utilities). Results are committed so downstream work
can rely on them offline.

Usage:
    python scripts/atlas_entity_audit.py
    python scripts/atlas_entity_audit.py --symbols GPX4 FSP1 ACSL4
"""

import argparse
import json
import sys
import time
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_baseline import atlas_root  # noqa: E402
from atlas_graph import load_index, resolve  # noqa: E402
from config import PROJECT_ROOT  # noqa: E402

OUT = PROJECT_ROOT / "analysis" / "atlas-entity-audit.md"
RAW = PROJECT_ROOT / "analysis" / "atlas-entity-audit.json"

# Symbols this project actually queries: the ferroptosis core, its defences,
# the immune coupling, and the delivery/transport genes.
SYMBOLS = [
    "GPX4", "FSP1", "AIFM2", "SLC7A11", "SLC3A2", "ACSL4", "LPCAT3", "ALOX15",
    "ALOX12", "ALOX5", "NFE2L2", "KEAP1", "DHODH", "GCH1", "FTH1", "FTL",
    "NCOA4", "PROM2", "TFRC", "SCD", "MBOAT1", "MBOAT2", "FAR1", "AGPS",
    "POR", "CYB5R1", "DHCR7", "EBP", "SC5D", "VKORC1L1", "ATP7A", "ATP7B",
    "CHMP5", "CHMP6", "CDH1", "NF2", "YAP1", "IFNG", "CD274", "PDCD1",
    "CTLA4", "HDAC1", "TP53", "KRAS", "EGFR", "ERBB2", "BRCA1", "BRCA2",
    "PARP1", "CDKN2A", "MKI67", "S100A4", "ATL1",
]


def ncbi_gene(ids: list) -> dict:
    """id -> (symbol, description) from NCBI, batched."""
    out = {}
    for i in range(0, len(ids), 100):
        batch = [x for x in ids[i:i + 100] if str(x).isdigit()]
        if not batch:
            continue
        url = ("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
               f"?db=gene&id={','.join(batch)}&retmode=json")
        req = urllib.request.Request(url, headers={"User-Agent": "cancer_research-atlas/1.0"})
        with urllib.request.urlopen(req, timeout=90) as r:
            res = json.loads(r.read())["result"]
        for gid in batch:
            d = res.get(gid)
            if d:
                out[gid] = (d.get("name", ""), d.get("description", ""))
        time.sleep(0.4)
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--symbols", nargs="*", default=None)
    args = ap.parse_args()
    symbols = args.symbols or SYMBOLS

    idx = load_index(atlas_root())
    assigned = {s: resolve(idx, s) for s in symbols}
    gene_ids = sorted({v for v in assigned.values() if v and str(v).isdigit()})
    print(f"resolving {len(gene_ids)} identifiers against NCBI ...", flush=True)
    ncbi = ncbi_gene(gene_ids)

    rows = []
    for s in symbols:
        gid = assigned[s]
        if not gid:
            rows.append(dict(symbol=s, gid=None, ncbi_symbol=None, desc=None, status="unresolved"))
            continue
        if not str(gid).isdigit():
            rows.append(dict(symbol=s, gid=gid, ncbi_symbol=None, desc=None, status="non-gene"))
            continue
        sym, desc = ncbi.get(str(gid), ("", ""))
        ok = sym.upper() == s.upper()
        rows.append(dict(symbol=s, gid=gid, ncbi_symbol=sym, desc=desc,
                         status="ok" if ok else "MISMATCH"))

    bad = [r for r in rows if r["status"] == "MISMATCH"]
    unres = [r for r in rows if r["status"] == "unresolved"]
    RAW.write_text(json.dumps(rows, indent=1), encoding="utf-8")

    L = [
        "# Gene-name resolution audit for the atlas graph (#ATLAS)", "",
        "Generated by `scripts/atlas_entity_audit.py`. Requires network; results are",
        "committed so downstream work can rely on them offline.", "",
        "## Why", "",
        "A literature knowledge graph is only as good as its entity resolution, and gene",
        "symbols collide badly. Found the hard way: PubTator3 maps 357 mentions of `FSP1`",
        "and 90 of `ferroptosis suppressor protein 1` to NCBI Gene **51062**, which is",
        "**ATL1 (atlastin GTPase 1)**, a hereditary spastic paraplegia gene unrelated to",
        "ferroptosis. The real FSP1 is **84883 (AIFM2)**. That collision sits directly",
        "under the manuscript's headline GPX4+FSP1 Bliss-synergy claim: querying the graph",
        "for `FSP1` returns ATL1's edges.", "",
        f"## Result: {len(bad)} mismatches out of {len(rows)} symbols checked", "",
        "| queried symbol | PubTator gene id | NCBI calls it | status |",
        "|---|---|---|---|",
    ]
    for r in rows:
        gid = r["gid"] or "-"
        ncbi_s = r["ncbi_symbol"] or "-"
        mark = "**MISMATCH**" if r["status"] == "MISMATCH" else r["status"]
        L.append(f"| `{r['symbol']}` | {gid} | {ncbi_s} | {mark} |")

    if bad:
        L += ["", "## Mismatches in detail", ""]
        for r in bad:
            L += [f"* **`{r['symbol']}` -> gene {r['gid']} = {r['ncbi_symbol']}** "
                  f"({r['desc']}).",
                  "  Any query using this symbol returns the wrong gene's edges.", ""]
    if unres:
        L += ["", "## Unresolved", "",
              "These symbols have no attested surface form in the entity files, so they",
              "cannot be queried at all:", ""]
        L += [f"* `{r['symbol']}`" for r in unres] + [""]

    L += ["## How to use this", "",
          "Query by **identifier**, not symbol, for anything load-bearing. The atlas",
          "graph accepts an identifier directly (`--pair 84883 2879`). Where a symbol must",
          "be used, check it here first.", "",
          "This audit covers only the symbols this project queries. It is a spot check,",
          "not a proof that the rest of the graph is clean -- the base rate of this class",
          "of error across 168,385 identifiers is unmeasured.", ""]

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"{len(bad)} MISMATCH, {len(unres)} unresolved, {len(rows)} checked")
    for r in bad:
        print(f"  MISMATCH  {r['symbol']:<12} -> gene {r['gid']} = {r['ncbi_symbol']} ({r['desc'][:44]})")


if __name__ == "__main__":
    main()
