#!/usr/bin/env python3
"""Atlas: measure the frozen corpus against the cancer census (#ATLAS).

The frozen corpus was built from 19 keyword queries. This asks, for the first
time with a denominator: what fraction of the cancer literature does it hold,
and is that fraction representative?

Every number the manuscript reports about where research is concentrated is a
ratio whose denominator was previously unknown. This supplies the denominator.

Reads `corpus/atlas/records/*.jsonl.gz` (the census, built by
`scripts/atlas_baseline.py`) and `corpus/INDEX.jsonl` (the frozen corpus).
Writes `analysis/atlas-coverage.md`. Read-only with respect to both.

Streaming and stdlib only, so it runs on a partial census while the ingest is
still going -- the report states how complete the census was when it ran.

Usage:
    python scripts/atlas_coverage.py
"""

import collections
import gzip
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import PROJECT_ROOT  # noqa: E402
from atlas_baseline import atlas_root  # noqa: E402

FROZEN = PROJECT_ROOT / "corpus" / "INDEX.jsonl"
OUT = PROJECT_ROOT / "analysis" / "atlas-coverage.md"

# Topics the project's own thesis rests on. The frozen corpus has no query and
# no mechanism tag for the first two, so their true size has never been known.
PROBE_TOPICS = {
    "ferroptosis": r"\bferroptos",
    "photodynamic therapy": r"\bphotodynamic\b",
    "sonodynamic therapy": r"\bsonodynamic\b",
    "tumor treating fields": r"\b(tumou?r[- ]treating fields|ttfields)\b",
    "CAR-T": r"\b(car[- ]t\b|chimeric antigen receptor)",
    "immune checkpoint": r"\b(checkpoint inhibitor|pd-1|pd-l1|ctla-4)\b",
    "nanoparticle": r"\bnanoparticle",
    "CRISPR": r"\bcrispr\b",
    "oncolytic virus": r"\boncolytic\b",
    "PROTAC / degrader": r"\b(protac|targeted protein degrad)",
}


def iter_census(root: Path):
    files = sorted((root / "records").glob("*.jsonl.gz"))
    for f in files:
        with gzip.open(f, "rt", encoding="utf-8") as fh:
            for line in fh:
                yield json.loads(line)
    return


def main() -> None:
    root = atlas_root()
    rec_dir = root / "records"
    if not rec_dir.exists():
        raise SystemExit(f"no census at {rec_dir}; run scripts/atlas_baseline.py first")

    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    parsed = sum(1 for s in manifest["files"].values() if s.get("parsed"))
    total_files = 1334  # baseline file count at time of writing; reported, not assumed

    probes = {k: re.compile(v, re.I) for k, v in PROBE_TOPICS.items()}
    census_pmids = set()
    census_years = collections.Counter()
    census_topic = collections.Counter()
    census_desc = collections.Counter()
    census_pmc = 0
    census_abs = 0
    n = 0

    for r in iter_census(root):
        n += 1
        census_pmids.add(r["pmid"])
        if r.get("year"):
            census_years[r["year"]] += 1
        if r.get("pmcid"):
            census_pmc += 1
        if r.get("abstract"):
            census_abs += 1
        for u in r.get("cancer_ui", []):
            census_desc[u] += 1
        blob = f"{r.get('title','')} {r.get('abstract','')}"
        for name, rx in probes.items():
            if rx.search(blob):
                census_topic[name] += 1

    frozen_pmids, frozen_years, frozen_mech = set(), collections.Counter(), collections.Counter()
    with FROZEN.open(encoding="utf-8") as fh:
        for line in fh:
            row = json.loads(line)
            frozen_pmids.add(row["pmid"])
            if row.get("year"):
                frozen_years[row["year"]] += 1
            for m in row.get("mechanisms", []) or []:
                frozen_mech[m] += 1

    overlap = frozen_pmids & census_pmids
    mesh_labels = {}
    mesh_file = root / "mesh" / "c04-descriptors.tsv"
    if mesh_file.exists():
        for line in mesh_file.read_text(encoding="utf-8").splitlines():
            if line and not line.startswith("#") and "\t" in line:
                ui, lab = line.split("\t", 1)
                mesh_labels[ui] = lab

    complete = parsed >= total_files
    year_span = (min(census_years), max(census_years)) if census_years else (0, 0)

    L = [
        "# The frozen corpus measured against the cancer census (#ATLAS)", "",
        "Generated by `scripts/atlas_coverage.py`. Read-only.", "",
        f"**Census: {parsed}/{total_files} baseline files "
        f"({parsed/total_files:.1%}), {n:,} cancer articles.**", "",
        "PubMed reports 4,276,707 articles under `neoplasms[mh]`. The C04 pass landed at",
        "4,203,236, i.e. 98.3% of that, which is the check that the local MeSH filter",
        "reproduces NLM's own tree explosion. The census EXCEEDS the C04 reference",
        "because the definition was then extended past tree C04 with nine adjacent",
        "experimental-context descriptors -- so it should not be read as agreeing with,",
        "or overshooting, `neoplasms[mh]`. See `analysis/atlas-README.md`.", "",
    ]

    L += ["> " + (

        "**Per-mechanism capture is conditioned on having a tag.** The mechanism layer reaches 5.98% of the cancer literature, so the capture spread here is variation inside that fraction. See `analysis/atlas-taxonomy-reach.md` (#730)."), ""]
    if not complete:
        L += [
            "> ## PARTIAL CENSUS — DO NOT READ THE TABLES BELOW AS FIELD SIZES",
            ">",
            "> PubMed baseline files are ordered **chronologically**, not randomly. This",
            f"> run covers files 1-{parsed} of {total_files}, which is the *oldest*"
            f" literature: the",
            f"> articles here span {year_span[0]}-{year_span[1]}.",
            ">",
            "> Any topic that post-dates that window reads as zero because it had not been",
            "> invented yet, not because it is small. Ferroptosis was named in 2012; CAR-T,",
            "> CRISPR and checkpoint blockade are all later than the early files. A zero in",
            "> the topic table below is an artifact of ingest progress.",
            ">",
            "> Re-run this script once `scripts/atlas_baseline.py` reports"
            f" {total_files}/{total_files} files.",
            "",
        ]

    L += [
        "## Size", "",
        "| | articles |",
        "|---|---|",
        f"| census | {n:,} |",
        f"| frozen corpus | {len(frozen_pmids):,} |",
        f"| frozen records also in the census | {len(overlap):,} |",
        f"| census articles with an abstract | {census_abs:,} ({census_abs/max(n,1):.1%}) |",
        f"| census articles with a PMC identifier | {census_pmc:,} "
        f"({census_pmc/max(n,1):.1%}) |", "",
        "The PMC share UPPER-BOUNDS any full-text analysis; it is not the amount of text",
        "actually obtainable. A PMC identifier is necessary but not sufficient for an",
        "article to be in the redistributable open-access subset, and the actual pull",
        "retrieved fewer. The frozen corpus is 98.7% open access, which is not what the",
        "literature looks like.", "",
        "## Topic sizes the frozen corpus could not measure", "",
        "The frozen corpus has no query and no mechanism tag for ferroptosis or",
        "photodynamic therapy, so it could never state their size. Matched here on",
        "title+abstract across the census.", "",
        "| topic | census articles | share of census |",
        "|---|---|---|",
    ]
    for name in PROBE_TOPICS:
        c = census_topic.get(name, 0)
        L.append(f"| {name} | {c:,} | {c/max(n,1):.2%} |")

    L += ["", "## Most-indexed cancer descriptors in the census", "",
          "| MeSH descriptor | articles |", "|---|---|"]
    for ui, c in census_desc.most_common(20):
        L.append(f"| {mesh_labels.get(ui, ui)} | {c:,} |")

    L += ["", "## Temporal shape", "",
          "The frozen corpus was retrieved with date windows on some mechanisms and not",
          "others, so its year distribution is a retrieval artifact. The census is the",
          "real one.", "",
          "| decade | census | frozen |", "|---|---|---|"]
    dec = collections.Counter()
    for y, c in census_years.items():
        dec[(y // 10) * 10] += c
    fdec = collections.Counter()
    for y, c in frozen_years.items():
        fdec[(y // 10) * 10] += c
    for d in sorted(set(dec) | set(fdec)):
        L.append(f"| {d}s | {dec.get(d,0):,} | {fdec.get(d,0):,} |")

    # --- What the census says about the frozen corpus itself ---
    if complete:
        import re as _re
        from atlas_unindexed import is_cancer_text
        not_in = [p for p in frozen_pmids if p not in census_pmids]
        no_mesh = indexed_other = offtopic = offtopic_untagged = 0
        frozen_rows = {}
        with FROZEN.open(encoding="utf-8") as fh:
            for line in fh:
                r = json.loads(line)
                frozen_rows[r["pmid"]] = r
        for p in not_in:
            fp = PROJECT_ROOT / "corpus" / "by-pmid" / f"{p}.md"
            if not fp.exists():
                continue
            body = fp.read_text(errors="ignore")[:9000]
            mm = _re.search(r"^mesh_terms:\s*(\[\]|\n((?:- .*\n)+))", body, _re.M)
            if not mm or mm.group(1).strip() == "[]":
                no_mesh += 1
                continue
            indexed_other += 1
            ab = _re.search(r"## Abstract\n\n?(.*?)(?=\n## |\Z)", body, _re.S)
            title = frozen_rows.get(p, {}).get("title", "")
            if not is_cancer_text(title, ab.group(1) if ab else ""):
                offtopic += 1
                if not (frozen_rows.get(p, {}).get("mechanisms") or []):
                    offtopic_untagged += 1

        nf = len(frozen_pmids)
        L += [
            "", "## What the census says about the frozen corpus", "",
            f"{len(not_in):,} of {nf:,} frozen records ({len(not_in)/nf:.1%}) are absent from the",
            "census. Splitting them is informative, because the two causes point in opposite",
            "directions:", "",
            "| cause | n | share of frozen corpus |", "|---|---|---|",
            f"| not yet MeSH-indexed (recent, concentrated 2022-2026) | {no_mesh:,} | {no_mesh/nf:.1%} |",
            f"| indexed by NLM, but under no C04 descriptor | {indexed_other:,} | {indexed_other/nf:.1%} |",
            "",
            "The first is the census's blind spot and is recovered by",
            "`scripts/atlas_unindexed.py`.",
            "",
            "The second cuts the other way and is a limit of the C04 definition itself: of",
            f"those {indexed_other:,}, **{indexed_other-offtopic:,} ({(indexed_other-offtopic)/max(indexed_other,1):.0%}) are cancer papers by text**, which NLM",
            "indexed under other trees (drug, enzyme, method) with cancer only as application",
            "context. So a pure C04 filter loses roughly",
            f"{(indexed_other-offtopic)/nf:.1%} of a hand-built cancer corpus. Neither a keyword",
            "corpus nor a MeSH census is a superset of the other.",
            "",
            f"The residue -- **{offtopic} records ({offtopic/nf:.1%})** -- is genuinely not cancer:",
            "pulsed-electromagnetic-field studies of bone healing and pain, mRNA vaccines for",
            "COVID/Shigella/chikungunya, CRISPR method papers, bioelectric developmental",
            "biology.",
            "",
            f"**{offtopic_untagged} of those {offtopic} ({offtopic_untagged/max(offtopic,1):.0%}) carry no mechanism tag at all.** That",
            "matters for attributing blame: the mechanism tagger correctly declined to tag",
            "them, so this is a QUERY-level defect in `scripts/queries.txt` pulling non-cancer",
            "literature, distinct from the tag-level precision problem measured in",
            "`analysis/mechanism-precision-report.md`. The two defects share themes (PEMF,",
            "vaccines, CRISPR) but they are separate and need separate fixes.", "",
        ]

    L += ["", "## What this changes", "",
          "1. Every mechanism count in the manuscript is a numerator without a",
          "   denominator. The census supplies it, and the ratios can finally be stated",
          "   as coverage rather than as volume.",
          "2. Topics absent from the 19 queries are not small; they were simply never",
          "   asked for. The table above is the first measurement of their size.",
          "3. The open-access share of the census bounds every full-text claim the",
          "   project can ever make, and it is far below the frozen corpus's 98.7%.", ""]

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"census so far: {n:,} articles from {parsed}/{total_files} baseline files")
    print(f"frozen corpus: {len(frozen_pmids):,}; overlap: {len(overlap):,}")
    for name in PROBE_TOPICS:
        print(f"  {name:24} {census_topic.get(name,0):>8,}")


if __name__ == "__main__":
    main()
