#!/usr/bin/env python3
"""Where does this project's thesis actually sit in the literature? (#ATLAS-THESIS)

WHY
---
The manuscript argues that ferroptosis induction in drug-tolerant persister
cells, reached by physical ROS-generating modalities (sonodynamic therapy above
all), is a direction worth testing. It argues this from a 4,830-article corpus
that contains **no ferroptosis query and no photodynamic-therapy query at all** --
the two topics its own simulation half is built on. So the corpus could not, even
in principle, say how much work exists on the thesis or whether it is growing.

The census can. MeSH carries a `Ferroptosis` descriptor, so the intersections
this project's argument depends on are directly countable across 4,403,994
cancer articles.

WHAT IT MEASURES
----------------
Ferroptosis-indexed cancer articles, and their intersection with the modality
and resistance concepts the thesis chains together. Per year, so growth is
visible and a thin intersection can be told from a new one.

WHY THAT MATTERS EITHER WAY
---------------------------
A thin intersection is not a refutation. It is what an under-explored direction
looks like, which is the manuscript's own claim. But it is also the difference
between "few people have tried this" and "this is well supported", and the
manuscript should be able to say which -- with a number rather than an
impression.

Usage:
    python scripts/atlas_thesis_position.py
"""

import collections
import glob
import gzip
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_baseline import atlas_root  # noqa: E402
from config import PROJECT_ROOT  # noqa: E402

OUT = PROJECT_ROOT / "analysis" / "atlas-thesis-position.md"
RAW = PROJECT_ROOT / "analysis" / "atlas-thesis-position.json"

CORE = {"Ferroptosis"}
# Each leg of the thesis chain, as MeSH concepts.
LEGS = {
    "sonodynamic therapy": {"Ultrasonic Therapy"},
    "photodynamic therapy": {"Photochemotherapy", "Photosensitizing Agents"},
    "focused ultrasound": {"High-Intensity Focused Ultrasound Ablation"},
    "drug resistance": {"Drug Resistance, Neoplasm"},
    "immunotherapy": {"Immune Checkpoint Inhibitors"},
    "lipid peroxidation": {"Lipid Peroxidation"},
}
# The census's last year is partial and MeSH indexing lags publication, so the
# most recent year is reported but never used for a growth claim.
PARTIAL_TAIL = 1


def main() -> int:
    root = atlas_root()
    per_year = collections.defaultdict(collections.Counter)
    totals = collections.Counter()
    n = 0
    files = sorted(glob.glob(str(root / "records" / "*.jsonl.gz")))
    print(f"scanning {len(files):,} census shards ...", flush=True)
    for i, f in enumerate(files, 1):
        with gzip.open(f, "rt", encoding="utf-8") as fh:
            for line in fh:
                r = json.loads(line)
                n += 1
                m = set(r.get("mesh") or [])
                y = r.get("year")
                if not m or not y or not (m & CORE):
                    continue
                totals["ferroptosis"] += 1
                per_year[y]["ferroptosis"] += 1
                for leg, descs in LEGS.items():
                    if m & descs:
                        totals[leg] += 1
                        per_year[y][leg] += 1
        if i % 400 == 0:
            print(f"  {i}/{len(files)}", flush=True)
    print(f"scanned {n:,} records", flush=True)

    yrs = sorted(y for y in per_year if per_year[y]["ferroptosis"])
    full = [y for y in yrs if y <= max(yrs) - PARTIAL_TAIL]
    growth = None
    if len(full) >= 6:
        a, b = full[-6], full[-1]
        n0, n1 = per_year[a]["ferroptosis"], per_year[b]["ferroptosis"]
        growth = (a, n0, b, n1, (n1 / n0) if n0 else None)

    L = [
        "# Where this project's thesis sits in the literature (#ATLAS-THESIS)", "",
        "Generated by `scripts/atlas_thesis_position.py`.", "",
        "The manuscript argues for ferroptosis induction in drug-tolerant persister",
        "cells, reached by physical ROS-generating modalities. It argues this from a",
        "4,830-article corpus containing **no ferroptosis query and no",
        "photodynamic-therapy query at all** -- the two topics its own simulation half",
        "is built on. That corpus could not say how much work exists on the thesis.",
        "The census can.", "",
        "## The field the thesis lives in", "",
        f"**{totals['ferroptosis']:,}** cancer articles in the census carry the MeSH",
        "`Ferroptosis` descriptor.",
    ]
    if growth:
        a, n0, b, n1, mult = growth
        L += ["",
              f"It is growing fast: **{n0:,}** in {a} to **{n1:,}** in {b}, "
              f"a factor of **{mult:.0f}** in {b-a} years."]
    L += [
        "", "## Each leg of the argument, counted", "",
        "| leg | articles with ferroptosis | share of the ferroptosis field |",
        "|---|---|---|",
    ]
    for leg in sorted(LEGS, key=lambda k: -totals[k]):
        L.append(f"| {leg} | {totals[leg]:,} | "
                 f"{100*totals[leg]/max(1,totals['ferroptosis']):.2f}% |")

    sdt = totals["sonodynamic therapy"]
    pdt = totals["photodynamic therapy"]
    res = totals["drug resistance"]
    L += [
        "", "## What this says about the thesis", "",
        f"The resistance leg is the strong one: **{res:,}** articles connect",
        "ferroptosis to neoplasm drug resistance, and that is the part of the",
        "argument the manuscript should lean on hardest.", "",
        f"The sonodynamic leg is **{sdt}** articles. In the entire indexed cancer",
        "literature. That is the thesis's own central mechanism, and it is close to",
        "unexplored territory rather than a contested one.", "",
        f"Photodynamic therapy, the modality the manuscript treats as the cautionary",
        f"precedent, has **{pdt:,}** -- about **{pdt/max(1,sdt):.0f}x** more. So the",
        "precedent is far better established than the thing it is a precedent for,",
        "which is exactly why the manuscript's own argument that PDT has not",
        "demonstrated the ROS-to-immunity chain carries weight.", "",
        "### Read this in both directions", "",
        "A thin intersection is not a refutation. It is what an under-explored",
        "direction looks like, and the manuscript claims precisely that. But it is",
        "also the difference between *few people have tried this* and *this is well",
        "supported*, and the manuscript can now say which with a number rather than",
        "an impression.", "",
        "The honest framing for the SDT leg is that it is a hypothesis with a handful",
        f"of supporting papers, not a literature. {sdt} articles cannot establish a",
        "mechanism, and the simulation work is therefore doing more of the argument's",
        "load than the citation count suggests.", "",
        "## By year", "",
        "| year | ferroptosis | + SDT | + PDT | + resistance |", "|---|---|---|---|---|",
    ]
    for y in yrs:
        if y < 2018:
            continue
        r = per_year[y]
        tail = "  *(partial / indexing lag)*" if y > max(yrs) - PARTIAL_TAIL else ""
        L.append(f"| {y}{tail} | {r['ferroptosis']:,} | {r['sonodynamic therapy']} | "
                 f"{r['photodynamic therapy']} | {r['drug resistance']} |")

    L += [
        "", "## Limits", "",
        "* MeSH indexing lags publication, so the most recent year understates every",
        "  column and is excluded from the growth figure rather than shown as a fall.",
        "* `Ultrasonic Therapy` is the closest MeSH concept to sonodynamic therapy and",
        "  is broader than it, so the SDT count is an OVER-estimate. The real",
        "  intersection is smaller than the number above, not larger.",
        "* An article can discuss a mechanism without being indexed for it. These are",
        "  lower bounds on discussion and upper bounds on nothing.",
        "* Co-occurrence of two descriptors is not a claim that the article connects",
        "  them, only that it is indexed for both.",
    ]

    OUT.write_text("\n".join(L) + "\n")
    RAW.write_text(json.dumps({
        "census_records": n, "totals": dict(totals),
        "growth": {"from_year": growth[0], "from_n": growth[1],
                   "to_year": growth[2], "to_n": growth[3],
                   "multiple": growth[4]} if growth else None,
        "by_year": {str(y): dict(per_year[y]) for y in yrs},
    }, indent=2) + "\n")
    print(f"\nferroptosis {totals['ferroptosis']:,}   xSDT {sdt}   xPDT {pdt}   "
          f"xresistance {res:,}")
    print(f"wrote {OUT}\nwrote {RAW}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
