#!/usr/bin/env python3
"""What do the discovery rankers actually SELECT? (#ATLAS-LBD-DEGREE)

WHY
---
`atlas_discovery_eval.py` measures how often each ranking predicts a pair the
literature went on to assert, and reports the orderings in a table with a
one-line gloss of what each method does. One of those glosses says the shipped
ABC ranking "divides out candidate degree".

That describes the MECHANISM -- the hypergeometric null does take `deg_c` as a
parameter, so a high-degree candidate needs more bridges to look surprising. It
does not describe the RESULT, and nothing measured the result. This does.

WHAT IT MEASURES
----------------
For each seed, `L(m)` = the mean degree of ranker m's top-k candidates divided
by the mean degree of the candidate pool it chose them from. `L = 1` is a
degree-neutral ranker. `L(popularity)` is the ceiling by construction, since
popularity IS degree.

THE POINT OF NORMALISING BY THE POOL. A ranker can look hub-biased simply
because the pool is hubby -- 2-hop bridging through non-hub intermediates still
lands on well-connected candidates. Dividing by the pool mean asks the only
question that separates the ranker from its input: given these candidates, does
this method prefer the well-connected ones?

WHY IT RUNS ON THE SPLIT GRAPH AND NOT THE CURRENT ONE
--------------------------------------------------------
The precision numbers come from a graph rebuilt as it stood BEFORE the split
year. Computing L on today's graph and quoting it beside those precisions would
compare two different worlds -- the same error that let a sibling analysis in
this repo silently invert its own finding when a live artifact moved underneath
it. So this reuses the harness's own `pair_first_year`, split, seed sample and
candidate construction, and every number here describes the same build the
precisions do.

WHAT IT CANNOT SAY
------------------
Nothing about whether hub-selection is WRONG. Well-connected entities may
genuinely be likelier to acquire a true new relation, and that is not separable
here: a latent importance drives degree, exposure and real biology together.
This measures what the rankers select, not whether selecting it is a mistake.

Usage:
    python scripts/atlas_discovery_degree_bias.py
    python scripts/atlas_discovery_degree_bias.py --seeds 60
    python scripts/atlas_discovery_degree_bias.py --render-only
"""

import argparse
import collections
import json
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_baseline import atlas_root  # noqa: E402
from atlas_discovery_eval import (  # noqa: E402
    SEED_RNG, load_corrections, load_index, pair_first_year, pmid_years, rank_all,
)
from config import PROJECT_ROOT  # noqa: E402

OUT_MD = PROJECT_ROOT / "analysis" / "atlas-discovery-degree-bias.md"
OUT_JSON = PROJECT_ROOT / "analysis" / "atlas-discovery-degree-bias.json"

METHODS = ("abc", "popularity", "adamic_adar", "resource_alloc",
           "jaccard", "bridges", "random")


def _spearman(xs: list, ys: list) -> float:
    """Rank correlation, stdlib only, with proper tie averaging."""
    def rank(v):
        order = sorted(range(len(v)), key=lambda i: v[i])
        r = [0.0] * len(v)
        i = 0
        while i < len(order):
            j = i
            while j + 1 < len(order) and v[order[j + 1]] == v[order[i]]:
                j += 1
            avg = (i + j) / 2 + 1
            for k in range(i, j + 1):
                r[order[k]] = avg
            i = j + 1
        return r
    if len(xs) < 3:
        return 0.0
    rx, ry = rank(xs), rank(ys)
    n = len(xs)
    mx, my = sum(rx) / n, sum(ry) / n
    num = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    den = (sum((a - mx) ** 2 for a in rx) * sum((b - my) ** 2 for b in ry)) ** 0.5
    return num / den if den else 0.0


def render(raw: dict) -> str:
    """Render the retained degree-selectivity snapshot without a graph rebuild.

    The stored metrics and evaluation precision belong to the original shared
    graph. Offline rendering preserves those measurements; it does not recompute
    candidate rankings or verify their identity against an unavailable graph.
    """
    json.dumps(raw, allow_nan=False)
    med = raw["median_L"]
    if (not isinstance(med, dict) or set(med) != set(METHODS)
            or any(type(value) not in (int, float) or value < 0 for value in med.values())):
        raise ValueError("degree-selectivity snapshot requires all seven nonnegative medians")
    share = raw["share_of_popularity"]
    prec = raw["precision_at_k"]
    rho_all = raw["spearman_L_vs_precision"]
    rho_real = raw["spearman_L_vs_precision_excluding_random"]
    L = [
        "# What the discovery rankers actually select (#ATLAS-LBD-DEGREE)", "",
        "Generated by `scripts/atlas_discovery_degree_bias.py`.", "",
        "The original discovery evaluation described the ranking formulas' degree",
        "corrections. This retained study measures how much degree selectivity",
        "remains in their actual selections on the same graph and candidate pools.",
        "The hypergeometric null includes candidate degree; that alone does not",
        "establish how degree-selective the resulting ranking will be.", "",
        "Offline `--render-only` reproduces this text from retained metrics. It",
        "does not rebuild the graph, rerank candidates, or rewrite the numerical",
        "snapshot. The separate evaluation can reconstruct its hit summaries",
        "and paired intervals from its stored per-seed counts.", "",
        "## The measurement", "",
        "`L` is the mean degree of a ranker's top-"
        f"{raw['top']} divided by the mean degree of the candidate pool it drew them",
        "from, over the same seeds, the same split and the same pools the precision",
        "table uses. `L = 1` is degree-neutral. `popularity` is the ceiling by",
        "construction, because popularity IS degree.", "",
        f"| ranking | median L | share of popularity's selectivity |",
        "|---|---|---|",
    ]
    for m in sorted(med, key=lambda k: (-med[k], k)):
        s = f"{100*share[m]:.0f}%" if m in share else "--"
        L.append(f"| {m} | **{med[m]:.1f}x** | {s} |")

    abc_L, pop_L = med.get("abc", 0), med.get("popularity", 0)
    L += [
        "", "## What it says", "",
        f"**The correction is real and it is large.** ABC sits at {abc_L:.1f}x "
        f"against popularity's {pop_L:.1f}x, reproducing only "
        f"{100*share.get('abc', 0):.0f}% of the",
        "selectivity of ranking by degree itself. Jaccard normalises so hard it",
        "lands BELOW the pool average in this snapshot.", "",
        "**Observed selectivity and precision.** The original evaluation already suspected this",
        "association from the formulas' intended corrections. This table measures selection",
        "on the retained graph, alongside each method's future-assertion precision:", "",
        f"| ranking | median L | precision@{raw['top']} |", "|---|---|---|",
    ] + [
        f"| {m} | {med[m]:.1f}x | {100*prec[m]:.1f}% |"
        for m in sorted(med, key=lambda k: (-med[k], k)) if m in prec
    ] + [
        "",
        f"Rank correlation between L and precision is **{rho_all:.2f}** over all",
        f"{len(med)} methods"
        + ("" if rho_all >= 0.999 else
           f" and **{rho_real:.2f}** over the {len(med)-1} that carry any signal")
        + ".",
    ] + ([
        "`random` sits exactly where a degree-neutral ranking should, at 1.0x, and",
        "`jaccard` -- the only method that corrects PAST neutral -- is the only one",
        "that scores below it. A ranking anti-correlated with what the target",
        "rewards doing worse than no ranking at all is what that looks like.", "",
    ] if rho_all >= 0.999 else [
        "The exception is `random`, which is degree-neutral by construction rather",
        "than by correction and has nothing to rank with; it is the one point where",
        "a low L does not mean the method corrected for degree.", "",
    ]) + [
        "**Scope of the ordering.** These methods cover different degrees of hub",
        "selection in this snapshot. Their observed association with precision",
        "does not rule out other ranking methods, combinations or evaluation targets.", "",
        "**What the comparison establishes.** Every ranking, including the random",
        "baseline, uses the same candidate pool. Differences measure ordering",
        "within that pool; they cannot establish whether the candidate generator",
        "improves on an unrestricted or alternative candidate set. That requires",
        "a separate candidate-selection control.", "",
        "The observed association between degree selectivity and future-assertion",
        "precision does not identify biological usefulness or the cause of the",
        "association. A method can lose on this literature-prediction endpoint",
        "without being shown to miss biologically useful overlooked connections.", "",
        "## What this does NOT say", "",
        "**It does not show hub-selection is wrong.** Well-connected entities may",
        "genuinely be likelier to acquire a true new relation, and nothing here",
        "separates that from the target rewarding exposure: a latent importance",
        "drives degree, how much gets written, and real biology together. Two",
        "independent critiques of this design concluded that separation is not",
        "identifiable from this corpus at any sample size, because every available",
        "exposure measure is either the outcome measured through the same extractor",
        "or is the treatment itself.", "",
        "**And it is six points.** The rank correlation is over six methods, not six",
        "hundred. It is a near-perfect ordering rather than a well-powered estimate,",
        "and it would be worth little if the ordering were not this clean or if the",
        "methods were not spread across the whole range from 0.1x to 7.4x.", "",
        f"Computed over {raw['seeds_evaluated']} seeds at split {raw['split']}.", "",
    ]
    return "\n".join(L) + "\n"


def main(argv=None) -> int:
    import random

    from atlas_discovery import HUB_PERCENTILE  # noqa: E402
    from atlas_discovery_eval import SEED_DEGREE_MAX, SEED_DEGREE_MIN

    ap = argparse.ArgumentParser()
    ap.add_argument("--split", type=int, default=2018)
    ap.add_argument("--seeds", type=int, default=200)
    ap.add_argument("--top", type=int, default=20)
    ap.add_argument("--render-only", action="store_true",
                    help="render the retained snapshot without rebuilding the graph")
    args = ap.parse_args(argv)
    if min(args.split, args.seeds, args.top) <= 0:
        ap.error("--split, --seeds, and --top must be positive integers")
    if args.render_only:
        raw = json.loads(OUT_JSON.read_text(encoding="utf-8"))
        markdown = render(raw)
        OUT_MD.write_text(markdown, encoding="utf-8")
        print(f"wrote {OUT_MD}")
        return 0

    root = atlas_root()
    idx = load_index(root)
    years = pmid_years(root)
    first = pair_first_year(root, years, load_corrections())

    before = {k for k, y in first.items() if y < args.split}
    adj = collections.defaultdict(set)
    for a, b in before:
        adj[a].add(b)
        adj[b].add(a)
    degrees = {k: len(v) for k, v in adj.items()}
    cutoff = sorted(degrees.values())[int(len(degrees) * HUB_PERCENTILE)]
    n_nodes = len(degrees)

    # The SAME seeds the precision table uses: same RNG, same pool, same order.
    rng = random.Random(SEED_RNG)
    pool = sorted(k for k, d in degrees.items()
                  if SEED_DEGREE_MIN <= d <= SEED_DEGREE_MAX)
    seeds = rng.sample(pool, min(args.seeds, len(pool)))

    per_seed, ratios = [], {m: [] for m in METHODS}
    for sid in seeds:
        ranks = rank_all(adj, degrees, cutoff, n_nodes, sid, rng)
        if not ranks:
            continue
        cand_ids = ranks["abc"]                      # same set for every method
        pool_mean = statistics.mean(degrees.get(c, 0) for c in cand_ids)
        if pool_mean <= 0:
            continue
        row = {"seed": sid, "seed_name": idx["canon"].get(sid, sid),
               "candidates": len(cand_ids), "pool_mean_degree": pool_mean}
        for m in METHODS:
            top = ranks[m][:args.top]
            if not top:
                continue
            L = statistics.mean(degrees.get(c, 0) for c in top) / pool_mean
            row[m] = L
            ratios[m].append(L)
        per_seed.append(row)

    med = {m: statistics.median(v) for m, v in ratios.items() if v}
    # The precision leaderboard this is being compared against, read from the
    # evaluation's own artifact rather than restated.
    try:
        prec = json.loads(
            (PROJECT_ROOT / "analysis" / "atlas-discovery-eval.json").read_text()
        )["headline"]["precision"]
    except (OSError, ValueError, KeyError):
        prec = {}
    pairs = [(med[m], prec[m]) for m in med if m in prec]
    real = [(med[m], prec[m]) for m in med if m in prec and m != "random"]
    rho_all = _spearman([a for a, _ in pairs], [b for _, b in pairs])
    rho_real = _spearman([a for a, _ in real], [b for _, b in real])
    # How much of popularity's selectivity each method reproduces. 0 would be a
    # degree-neutral ranker, 1 is popularity itself.
    share = {m: (med[m] - 1) / (med["popularity"] - 1)
             for m in med if med.get("popularity", 1) > 1}

    raw = {
        "split": args.split, "top": args.top, "seeds_evaluated": len(per_seed),
        # Fingerprints the GRAPH, not just the split. See the dump script.
        "pairs_before": len(before),
        "median_L": med, "share_of_popularity": share,
        "precision_at_k": prec,
        "spearman_L_vs_precision": rho_all,
        "spearman_L_vs_precision_excluding_random": rho_real,
        "per_seed": per_seed[:200],
    }
    encoded = json.dumps(raw, indent=2, allow_nan=False) + "\n"
    markdown = render(raw)
    OUT_MD.write_text(markdown, encoding="utf-8")
    OUT_JSON.write_text(encoded, encoding="utf-8")
    print("median L: " + "  ".join(f"{m} {med[m]:.1f}x" for m in
                                   sorted(med, key=lambda k: -med[k])))
    print(f"wrote {OUT_MD}\nwrote {OUT_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
