#!/usr/bin/env python3
"""Build the v2 evidence tags as a PARALLEL, derived index (#TAGGER-V2).

WHY A PARALLEL INDEX
--------------------
`corpus/INDEX.jsonl` is the frozen snapshot every manuscript number is computed
from, and CI guards it byte-for-byte. The v2 evidence tagger is measurably more
accurate (2.59x error reduction held-out, 1.95x on the human-consensus subset),
but re-tagging the frozen corpus would move published figures and invalidate the
evidence-tier, weighted-evidence and open-access-bias analyses.

So this writes a DERIVED layer instead, following the same frozen-vs-addendum
separation `corpus/living/` uses for the living review:

  corpus/derived/evidence-v2/index.jsonl   pmid -> v2 tag, frozen tag, changed flag
  analysis/evidence-v2-corpus-delta.md     what the layer would change, and where

Nothing under `corpus/by-pmid/`, `corpus/INDEX.jsonl` or `tags/` is written.
`tests/test_evidence_v2.py` asserts that separation.

Consumers that want the more accurate tags join on `pmid`; consumers that must
reproduce the manuscript keep reading the frozen index. When the layer is
eventually promoted, this same script's output is the diff to review.

Usage:
    python scripts/build_evidence_v2_index.py
"""

import collections
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

# The v2 decision is read from the environment at import time, so set it before
# importing tag_articles. This script exists to produce v2 output; it never
# writes to the frozen corpus, so forcing the flag here is safe.
os.environ["FERRO_EVIDENCE_V2"] = "1"

import tag_articles  # noqa: E402
from article_io import load_article  # noqa: E402
from config import PROJECT_ROOT  # noqa: E402

FROZEN_INDEX = PROJECT_ROOT / "corpus" / "INDEX.jsonl"
PMID_DIR = PROJECT_ROOT / "corpus" / "by-pmid"
OUT_DIR = PROJECT_ROOT / "corpus" / "derived" / "evidence-v2"
OUT_INDEX = OUT_DIR / "index.jsonl"
DELTA_MD = PROJECT_ROOT / "analysis" / "evidence-v2-corpus-delta.md"

LEVELS = ["phase3-clinical", "phase2-clinical", "phase1-clinical", "clinical-other",
          "preclinical-invivo", "preclinical-invitro", "theoretical", ""]


def main() -> None:
    assert tag_articles.EVIDENCE_USE_V2, "v2 flag failed to take effect"

    frozen = {}
    with FROZEN_INDEX.open(encoding="utf-8") as fh:
        for line in fh:
            row = json.loads(line)
            frozen[row["pmid"]] = row.get("evidence_level", "") or ""

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    changed = collections.Counter()
    before = collections.Counter()
    after = collections.Counter()
    gained = lost = 0
    written = 0

    with OUT_INDEX.open("w", encoding="utf-8") as out:
        for pmid, old in sorted(frozen.items()):
            path = PMID_DIR / f"{pmid}.md"
            if not path.exists():
                continue
            fm, body = load_article(path)
            new = tag_articles.match_evidence_level(fm, tag_articles.get_evidence_text(fm, body)) or ""
            before[old] += 1
            after[new] += 1
            if new != old:
                changed[(old, new)] += 1
                if old == "" and new:
                    gained += 1
                elif old and new == "":
                    lost += 1
            out.write(json.dumps({
                "pmid": pmid,
                "evidence_level_v2": new,
                "evidence_level_frozen": old,
                "changed": new != old,
            }, ensure_ascii=False) + "\n")
            written += 1

    total_changed = sum(changed.values())
    lines = [
        "# Evidence tagger v2: what it would change in the corpus (#TAGGER-V2)", "",
        "Generated by `scripts/build_evidence_v2_index.py`. Offline and deterministic.", "",
        "This is a DERIVED layer. `corpus/INDEX.jsonl` and `tags/` are untouched, so every",
        "manuscript number still reproduces. The tags live at",
        "`corpus/derived/evidence-v2/index.jsonl`, keyed by PMID.", "",
        f"- records processed: **{written}**",
        f"- predictions that differ from the frozen tag: **{total_changed} ({total_changed / written:.1%})**",
        f"- records that GAIN a tag (frozen was empty): **{gained}**",
        f"- records that LOSE a tag: **{lost}**", "",
        "## Distribution", "",
        "| evidence level | frozen | v2 | delta |", "|---|---|---|---|",
    ]
    for lv in LEVELS:
        label = lv or "_(untagged)_"
        b, a = before.get(lv, 0), after.get(lv, 0)
        lines.append(f"| {label} | {b} | {a} | {a - b:+d} |")

    lines += ["", "## Largest transitions", "", "| frozen | v2 | n |", "|---|---|---|"]
    for (old, new), n in changed.most_common(20):
        lines.append(f"| {old or '_(untagged)_'} | {new or '_(untagged)_'} | {n} |")

    lines += [
        "", "## How to read this", "",
        "The dominant transition is untagged -> tagged: the frozen tagger never read the",
        "stored full text, so it left 57.8% of records with no evidence level at all.",
        "That is the recall gap the v2 layer closes.",
        "",
        "These tags are more accurate on every evaluation set (see",
        "`analysis/evidence-v2-eval.md`), but they are NOT ground truth: annotator",
        "agreement on this task is only 77%, and the tiers that move most here",
        "(`theoretical`, and the in-vitro / in-vivo boundary) are exactly the ones two",
        "annotators disagree about most. Treat the layer as a better estimate, not a",
        "correction.", "",
        "Promotion checklist: `analysis/evidence-tagger-v2.md`.", "",
    ]
    DELTA_MD.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {OUT_INDEX} ({written} records)")
    print(f"wrote {DELTA_MD}")
    print(f"changed {total_changed}/{written} ({total_changed / written:.1%}); "
          f"gained a tag: {gained}; lost: {lost}")


if __name__ == "__main__":
    main()
