#!/usr/bin/env python3
"""Is there a calibration target for the unmodelled ferroptosis genes? (#616)

WHY
---
`analysis/atlas-model-gaps.md` asked the literature which ferroptosis mechanisms
it emphasises and found four with no parameter in `ferroptosis-core`: HMOX1
(1,583 ferroptosis-indexed articles), TP53 (1,497), TFRC (1,482), KEAP1 (768).

`CONTRIBUTING.md`'s layer policy requires a NAMED calibration target before any
new off-by-default axis lands. So the question is not "add four layers", it is
whether public data exists that could anchor them. The precedent is #444, which
shipped ACSL4 flagged DATA-GATED, and #462, which later anchored it against
cBioPortal TCGA expression.

WHAT THIS FINDS, INCLUDING ABOUT #462
--------------------------------------
The cBioPortal route does not work, and the reason applies retroactively.

Within-cohort mRNA z-scores are standardised per study by construction, so the
fraction of tumours below z = -1 is ~15.87% for ANY gene under approximate
normality. Measured across 32 TCGA PanCancer Atlas studies, all seven genes sit
within two points of that: ACSL4 14.4%, GPX4 14.5%, SLC7A11 16.0%, HMOX1 14.9%,
TP53 14.1%, TFRC 15.2%, KEAP1 13.8%.

That is the normal distribution being recovered, not a biological prior. So this
route cannot distinguish a gene whose low-expression tail matters from one whose
does not, and #462's reading of the same number as "the population prior for how
many tumours fall in the refractory-leaning tail" is weaker than stated -- the
figure would be the same for a gene with no role in ferroptosis at all.

One signal does survive: the DEEP tail and the spread across cancer types. TP53
sits at 4.3% below z = -2 against an expected 2.28% and the others' ~1.5-2.1%,
with much the widest inter-cancer spread. That is consistent with genuine TP53
loss in a subset of cancers rather than with standardisation.

Usage:
    python scripts/calibration_feasibility.py
"""

import csv
import json
import statistics
import sys
from math import erf, sqrt
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import PROJECT_ROOT  # noqa: E402

SRC = PROJECT_ROOT / "analysis" / "calibration" / "acsl4_prevalence_tcga.csv"
OUT = PROJECT_ROOT / "analysis" / "calibration" / "calibration-feasibility.md"
RAW = PROJECT_ROOT / "analysis" / "calibration" / "calibration-feasibility.json"

GAPS = ["HMOX1", "TP53", "TFRC", "KEAP1"]
ANCHORED = ["ACSL4", "GPX4", "SLC7A11"]
EXP_LOW = 0.5 * (1 + erf(-1 / sqrt(2)))
EXP_VLOW = 0.5 * (1 + erf(-2 / sqrt(2)))


def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}; run scripts/fetch_acsl4_prevalence.py", file=sys.stderr)
        return 1
    rows = list(csv.DictReader(SRC.open()))
    stats = {}
    for g in ANCHORED + GAPS:
        key = f"{g}_frac_low"
        if key not in rows[0]:
            continue
        lo = sorted(float(r[key]) for r in rows if r[key] not in ("", None))
        vl = [float(r[f"{g}_frac_verylow"]) for r in rows
              if r.get(f"{g}_frac_verylow") not in ("", None)]
        stats[g] = {
            "n_types": len(lo), "median_low": statistics.median(lo),
            "iqr_low": lo[int(.75 * len(lo))] - lo[int(.25 * len(lo))],
            "median_verylow": statistics.median(vl),
            "dev_from_normal": statistics.median(lo) - EXP_LOW,
        }

    L = [
        "# Is there a calibration target for the unmodelled genes? (#616)", "",
        "Generated by `scripts/calibration_feasibility.py`.", "",
        "`CONTRIBUTING.md`'s layer policy requires a named calibration target before",
        "any new off-by-default axis lands, so the question for the four mechanisms in",
        "`analysis/atlas-model-gaps.md` is whether public data could anchor them --",
        "not whether to write the layers.", "",
        "## The route that anchored ACSL4 does not work, and did not work then either",
        "",
        "cBioPortal mRNA z-scores are standardised WITHIN each study, so the fraction",
        f"of tumours below z = -1 is **{100*EXP_LOW:.2f}%** for any gene under",
        "approximate normality. Across 32 TCGA PanCancer Atlas studies:", "",
        "| gene | low-expression fraction | deviation from normal | spread (IQR) | below z=-2 |",
        "|---|---|---|---|---|",
    ]
    for g, s in stats.items():
        tag = " *(gap)*" if g in GAPS else ""
        L.append(f"| {g}{tag} | {100*s['median_low']:.1f}% | "
                 f"{100*s['dev_from_normal']:+.1f} | {100*s['iqr_low']:.1f} | "
                 f"{100*s['median_verylow']:.1f}% |")

    L += [
        "", "**Every gene lands within two points of the normal expectation.** That is",
        "the standardisation being recovered, not biology. The route cannot separate a",
        "gene whose low-expression tail matters from one with no role in ferroptosis,",
        "so it anchors none of the four.", "",
        "### What this adds to #462", "",
        "`analysis/calibration/acsl4-prevalence-calibration.md` already noted that the",
        "figure is a within-cohort number \"by construction (about a normal lower",
        "tail)\". What it lacked was a CONTROL, and without one it still presented",
        "10.8-18.8% as ACSL4's population prior. The six other genes are that control,",
        "and they show the figure is not ACSL4's -- it is the z-score's. Anything with",
        "a roughly normal expression distribution returns it, including a gene with no",
        "ferroptosis role at all.", "",
        "The ACSL4 layer's status-to-z-score BRIDGE is untouched: that maps a scale and",
        "is separately justified. What changes is that the prevalence number should be",
        "read as \"how the z-score partitions any cohort\", not as evidence about how",
        "many tumours are ACSL4-refractory. That distinction matters because the",
        "refractory phenotype is the thing the layer exists to stratify, and #462",
        "already found bulk mRNA does not rank it.", "",
        "## What does survive", "",
        f"The deep tail and the inter-cancer spread. TP53 sits at "
        f"{100*stats['TP53']['median_verylow']:.1f}% below z = -2 against an expected",
        f"{100*EXP_VLOW:.2f}% and the others' ~1.5-2.1%, with the widest spread across",
        "cancer types. That is consistent with real TP53 loss in a subset of cancers",
        "rather than with standardisation, and is the one gene here where an",
        "expression-derived prior would carry information.", "",
        "## Verdict per gene", "",
        "| gene | calibration status | reason |", "|---|---|---|",
        "| HMOX1 | **data-blocked** | no public dataset maps onto a model observable; "
        "expression prevalence is uninformative |",
        "| TFRC | **data-blocked** | same; the engine also already absorbs iron import "
        "into `ferritinophagy_release` |",
        "| KEAP1 | **data-blocked** | same; its effect is already carried by "
        "`nrf2_gsh_rate`, which it regulates |",
        "| TP53 | **weak anchor available** | deep-tail deviation is real, and CTRPv2 "
        "carries 828 cell lines x 5 ferroptosis inducers for a sensitivity join if a "
        "cell-line expression source can be obtained |", "",
        "None of the four should have a layer written on this evidence. The honest",
        "outcome is a data-blocked row, which is what #444 did for ACSL4 before #462",
        "found a partial anchor.", "",
        "## What would change the answer", "",
        "A cell-line expression matrix joinable to the committed CTRPv2 curves would",
        "make all four testable at once: correlate expression against ferroptosis-",
        "inducer EC50 across 828 lines. The DepMap download catalogue served that until",
        "recently and now returns HTML rather than the documented CSV, so the join is",
        "blocked on access, not on method.", "",
        "## Limits", "",
        "* Bulk tumour mRNA, which #462 already found does not rank the ACSL4-low",
        "  refractory phenotype the cell-line literature reports. The same caveat",
        "  applies with more force here.",
        "* Approximate normality is assumed when comparing to 15.87%. The observed",
        "  medians sit slightly below it for most genes, consistent with mild",
        "  right-skew in expression, and that does not change the conclusion.",
        "* A gene can matter enormously and have a flat expression distribution. This",
        "  measures whether THIS route informs a prior, not whether the gene matters.",
    ]

    OUT.write_text("\n".join(L) + "\n")
    RAW.write_text(json.dumps({
        "expected_low": EXP_LOW, "expected_verylow": EXP_VLOW,
        "genes": stats, "gaps": GAPS,
    }, indent=2) + "\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
