#!/usr/bin/env python3
"""Does full-text availability move the mechanism ranking? (#RETIRE-FROZEN)

WHY THIS REPLACES SECTION 3.3.1
-------------------------------
The manuscript asked whether restricting analysis to locally available full
text distorted its mechanism rankings, and answered it by comparing 4,830
full-text records against 5,586 abstract-only ones. The full-text side was
98.7% open access, which is not a contrast -- it is one side of a split with
almost nothing on the other, and a rank comparison across it could not have
detected much.

The census makes the same question answerable. 936,347 of 4,403,994 indexed
records (21.3%) carry a PMC identifier and 3,467,647 do not, so "does having
full text change what looks important" is a 936k-versus-3.47M comparison on
IDENTICAL expert labels. The mechanism definition does not change between the
two arms; the split is defined by PMC identifier presence.

WHAT THIS DOES AND DOES NOT SHOW
--------------------------------
It shows whether PMC identifier presence is associated with mechanism prevalence. It
does NOT show that the association is caused by access: publication era and
subject composition may contribute to identifier coverage. The
report therefore prints each mechanism's median year alongside its identifier rate, so
a reader can see the confound rather than take the ranking at face value.

Usage:
    python scripts/census_oa_bias.py
    python scripts/census_oa_bias.py --render-only
"""

import argparse
import json
import statistics
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from census_input import atlas_root, iter_census_records

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RECORDS = atlas_root() / "records"
MAP = PROJECT_ROOT / "analysis" / "mesh-mechanism-map.yaml"
OUT_MD = PROJECT_ROOT / "analysis" / "census-oa-bias.md"
OUT_JSON = PROJECT_ROOT / "analysis" / "census-oa-bias.json"


def load_map() -> dict:
    import yaml
    d = yaml.safe_load(MAP.read_text())
    return {k: {x.lower() for x in v["descriptors"]}
            for k, v in d["mechanisms"].items()}


def scan(stride: int = 1) -> dict:
    mech = load_map()
    have = Counter()
    lack = Counter()
    years = {k: [] for k in mech}
    n = n_have = 0
    for r in iter_census_records(RECORDS, stride):
        n += 1
        oa = bool(r.get("pmcid"))
        n_have += oa
        ms = {m.lower() for m in (r.get("mesh") or [])}
        if not ms:
            continue
        y = r.get("year")
        for k, descs in mech.items():
            if ms & descs:
                (have if oa else lack)[k] += 1
                if isinstance(y, int) and 1975 <= y <= 2026:
                    years[k].append(y)
    rows = []
    for k in mech:
        h, l = have[k], lack[k]
        if h + l == 0:
            continue
        ys = years[k]
        rows.append({
            "mechanism": k, "with_fulltext": h, "without": l, "total": h + l,
            "oa_rate": h / (h + l),
            "median_year": statistics.median(ys) if ys else None,
        })
    rows.sort(key=lambda r: -r["total"])
    return {"census": n, "with_pmcid": n_have,
            "census_oa_rate": n_have / n, "mechanisms": rows}


BIG_SHIFT = 3


def _rank(rows, key):
    """Competition ranks: equal counts share a rank; an empty arm has none."""
    if not any(r[key] > 0 for r in rows):
        return {r["mechanism"]: None for r in rows}
    ranks = {}
    previous = None
    rank = 0
    for position, row in enumerate(sorted(rows, key=lambda r: -r[key]), 1):
        if row[key] != previous:
            rank = position
            previous = row[key]
        ranks[row["mechanism"]] = rank
    return ranks


def derive(d: dict) -> dict:
    """Write the ranks and shifts INTO the artifact.

    They were computed at render time and stored nowhere, so this analysis's
    entire headline -- how many mechanisms move three or more places -- existed
    only as prose. Nothing downstream could check it, and a guard reading the
    JSON could not see the conclusion at all.
    """
    rows = d["mechanisms"]
    r_h = _rank(rows, "with_fulltext")
    r_l = _rank(rows, "without")
    for r in rows:
        m = r["mechanism"]
        r["rank_oa"] = r_h[m]
        r["rank_non_oa"] = r_l[m]
        r["shift"] = (r_l[m] - r_h[m]
                      if r_l[m] is not None and r_h[m] is not None else None)
    d["big_shift_threshold"] = BIG_SHIFT
    d["moved"] = (sorted(r["mechanism"] for r in rows
                         if abs(r["shift"]) >= BIG_SHIFT)
                  if rows and all(r["shift"] is not None for r in rows) else None)
    return d


def render(d: dict) -> str:
    d = derive(d)
    rows = d["mechanisms"]
    r_h = {r["mechanism"]: r["rank_oa"] for r in rows}
    r_l = {r["mechanism"]: r["rank_non_oa"] for r in rows}
    L = ["# Does full-text availability move the mechanism ranking?", ""]
    L += [f"*Generated by `scripts/census_oa_bias.py` over {d['census']:,} "
          f"MeSH-indexed census articles, of which {d['with_pmcid']:,} "
          f"({100*d['census_oa_rate']:.1f}%) carry a PMC identifier. Both arms "
          f"use the SAME expert descriptors; the split is defined by PMC "
          f"identifier presence.*", ""]
    L += ["The split measures **PMC identifier presence**, a proxy for full-text "
          "availability. This scan does not verify current access, an open-access "
          "licence, or a local full-text copy. The historical JSON field names "
          "`with_fulltext` and `oa_rate` retain this proxy meaning.", ""]
    L += [f"The superseded version of this test compared 4,830 full-text "
          f"records against 5,586 abstract-only ones, with the full-text side "
          f"98.7% open access. That is not a contrast. Here the split is "
          f"{d['with_pmcid']:,} against {d['census'] - d['with_pmcid']:,}.", ""]
    L += ["| mechanism | with PMC ID | without | PMC ID rate | rank, with ID | "
          "rank, without ID | shift | median year |",
          "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for r in rows:
        sh = r["shift"]
        mv = ("N/A" if sh is None else
              f"**{sh:+d}**" if abs(sh) >= BIG_SHIFT else f"{sh:+d}")
        rank_h = r_h[r["mechanism"]]
        rank_l = r_l[r["mechanism"]]
        my = f"{r['median_year']:.0f}" if r["median_year"] else "-"
        L.append(f"| `{r['mechanism']}` | {r['with_fulltext']:,} | "
                 f"{r['without']:,} | {100*r['oa_rate']:.1f}% | "
                 f"{rank_h if rank_h is not None else 'N/A'} | "
                 f"{rank_l if rank_l is not None else 'N/A'} | {mv} | {my} |")
    L += [""]
    if not rows:
        L += ["**Ranking comparison unavailable:** no mapped mechanism matched "
              "the selected records. This is an observed zero-match result, "
              "not evidence that the census input was unavailable.", ""]
    elif d["moved"] is None:
        L += ["**Ranking comparison unavailable:** at least one PMC-identifier "
              "arm has no mapped mechanism observations. Its ranks and the "
              "between-arm shifts are N/A; an empty comparison cannot establish "
              "ranking stability or movement.", ""]
    else:
        hi = max(rows, key=lambda r: r["oa_rate"])
        lo = min(rows, key=lambda r: r["oa_rate"])
        L += [f"**{len(d['moved'])} of {len(rows)} mechanisms shift {BIG_SHIFT} or more "
              f"positions** between the two arms. PMC identifier rate runs "
              f"{100*lo['oa_rate']:.1f}% (`{lo['mechanism']}`) to "
              f"{100*hi['oa_rate']:.1f}% (`{hi['mechanism']}`), against "
              f"{100*d['census_oa_rate']:.1f}% for the census as a whole.", ""]
    L += ["Equal counts share a competition rank (for example, 1, 1, 3). "
          "Zero counts tie below observed mechanisms within a populated arm; "
          "an arm with no mapped observations has no ranking.", ""]
    L += ["**The confound is in the last column and is not controlled here.** "
          "Identifier coverage may reflect publication era as well as subject "
          "and access. Read each identifier rate alongside its median year "
          "where dates are available. This comparison does not separate these "
          "effects or quantify an era contribution; it cannot attribute a "
          "ranking difference to access.", ""]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--render-only", action="store_true")
    ap.add_argument("--stride", type=int, default=1,
                    help="sample every Nth sorted shard (default: all shards)")
    a = ap.parse_args()
    if a.render_only:
        d = json.loads(OUT_JSON.read_text())
    else:
        d = scan(a.stride)
    # Derive BEFORE writing, so the ranks and shifts land in the artifact on
    # both paths. render() derives too and is idempotent; doing it here as well
    # is what makes --render-only refresh a stale artifact rather than only its
    # rendering.
    d = derive(d)
    json_text = json.dumps(d, indent=1, sort_keys=True) + "\n"
    markdown = render(d)
    OUT_JSON.write_text(json_text, encoding="utf-8")
    OUT_MD.write_text(markdown, encoding="utf-8")
    print(f"wrote {OUT_MD}\nwrote {OUT_JSON}")
    return 0


if __name__ == "__main__":
    main()
