#!/usr/bin/env python3
"""Does full-text availability move the mechanism ranking? (#RETIRE-FROZEN)

WHY THIS REPLACES SECTION 3.3.1
-------------------------------
The manuscript asked whether restricting analysis to locally available full
text distorted its mechanism rankings, and answered it by comparing 4,830
full-text records against 5,586 abstract-only ones. The full-text side was
98.7% open access, which is not a contrast -- it is one side of a split with
almost nothing on the other, and a rank comparison across it could not have
detected much.

The census makes the same question answerable. 936,347 of 4,403,994 indexed
records (21.3%) carry a PMC identifier and 3,467,647 do not, so "does having
full text change what looks important" is a 936k-versus-3.47M comparison on
IDENTICAL expert labels. The mechanism definition does not change between the
two arms; only availability does.

WHAT THIS DOES AND DOES NOT SHOW
--------------------------------
It shows whether OA availability is associated with mechanism prevalence. It
does NOT show that the association is caused by access: a field that publishes
in OA journals and a field that grows fast are confounded, because PMC
deposition rose steeply over the same years the newer mechanisms did. The
report therefore prints each mechanism's median year alongside its OA rate, so
a reader can see the confound rather than take the ranking at face value.

Usage:
    python scripts/census_oa_bias.py
    python scripts/census_oa_bias.py --render-only
"""

import argparse
import gzip
import json
import statistics
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RECORDS = PROJECT_ROOT / "corpus" / "atlas" / "records"
MAP = PROJECT_ROOT / "analysis" / "mesh-mechanism-map.yaml"
OUT_MD = PROJECT_ROOT / "analysis" / "census-oa-bias.md"
OUT_JSON = PROJECT_ROOT / "analysis" / "census-oa-bias.json"


def load_map() -> dict:
    import yaml
    d = yaml.safe_load(MAP.read_text())
    return {k: {x.lower() for x in v["descriptors"]}
            for k, v in d["mechanisms"].items()}


def scan() -> dict:
    mech = load_map()
    have = Counter()
    lack = Counter()
    years = {k: [] for k in mech}
    n = n_have = 0
    for f in sorted(RECORDS.glob("*.jsonl.gz")):
        with gzip.open(f, "rt", encoding="utf-8") as fh:
            for line in fh:
                r = json.loads(line)
                n += 1
                oa = bool(r.get("pmcid"))
                n_have += oa
                ms = {m.lower() for m in (r.get("mesh") or [])}
                if not ms:
                    continue
                y = r.get("year")
                for k, descs in mech.items():
                    if ms & descs:
                        (have if oa else lack)[k] += 1
                        if isinstance(y, int) and 1975 <= y <= 2026:
                            years[k].append(y)
    rows = []
    for k in mech:
        h, l = have[k], lack[k]
        if h + l == 0:
            continue
        ys = years[k]
        rows.append({
            "mechanism": k, "with_fulltext": h, "without": l, "total": h + l,
            "oa_rate": h / (h + l),
            "median_year": statistics.median(ys) if ys else None,
        })
    rows.sort(key=lambda r: -r["total"])
    return {"census": n, "with_pmcid": n_have,
            "census_oa_rate": n_have / n, "mechanisms": rows}


BIG_SHIFT = 3


def _rank(rows, key):
    return {r["mechanism"]: i + 1
            for i, r in enumerate(sorted(rows, key=lambda r: -r[key]))}


def derive(d: dict) -> dict:
    """Write the ranks and shifts INTO the artifact.

    They were computed at render time and stored nowhere, so this analysis's
    entire headline -- how many mechanisms move three or more places -- existed
    only as prose. Nothing downstream could check it, and a guard reading the
    JSON could not see the conclusion at all.
    """
    rows = d["mechanisms"]
    r_h = _rank(rows, "with_fulltext")
    r_l = _rank(rows, "without")
    for r in rows:
        m = r["mechanism"]
        r["rank_oa"] = r_h[m]
        r["rank_non_oa"] = r_l[m]
        r["shift"] = r_l[m] - r_h[m]
    d["big_shift_threshold"] = BIG_SHIFT
    d["moved"] = sorted(r["mechanism"] for r in rows
                        if abs(r["shift"]) >= BIG_SHIFT)
    return d


def render(d: dict) -> str:
    d = derive(d)
    rows = d["mechanisms"]
    r_h = {r["mechanism"]: r["rank_oa"] for r in rows}
    r_l = {r["mechanism"]: r["rank_non_oa"] for r in rows}
    L = ["# Does full-text availability move the mechanism ranking?", ""]
    L += [f"*Generated by `scripts/census_oa_bias.py` over {d['census']:,} "
          f"MeSH-indexed census articles, of which {d['with_pmcid']:,} "
          f"({100*d['census_oa_rate']:.1f}%) carry a PMC identifier. Both arms "
          f"use the SAME expert descriptors; only availability differs.*", ""]
    L += [f"The superseded version of this test compared 4,830 full-text "
          f"records against 5,586 abstract-only ones, with the full-text side "
          f"98.7% open access. That is not a contrast. Here the split is "
          f"{d['with_pmcid']:,} against {d['census'] - d['with_pmcid']:,}.", ""]
    L += ["| mechanism | with full text | without | OA rate | rank, OA | "
          "rank, non-OA | shift | median year |",
          "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for r in rows:
        sh = r_l[r["mechanism"]] - r_h[r["mechanism"]]
        mv = f"**{sh:+d}**" if abs(sh) >= 3 else f"{sh:+d}"
        my = f"{r['median_year']:.0f}" if r["median_year"] else "-"
        L.append(f"| `{r['mechanism']}` | {r['with_fulltext']:,} | "
                 f"{r['without']:,} | {100*r['oa_rate']:.1f}% | "
                 f"{r_h[r['mechanism']]} | {r_l[r['mechanism']]} | {mv} | {my} |")
    L += [""]
    moved = [r for r in rows if abs(r["shift"]) >= BIG_SHIFT]
    hi = max(rows, key=lambda r: r["oa_rate"])
    lo = min(rows, key=lambda r: r["oa_rate"])
    L += [f"**{len(moved)} of {len(rows)} mechanisms shift {BIG_SHIFT} or more "
          f"positions** between the two arms. OA rate runs "
          f"{100*lo['oa_rate']:.1f}% (`{lo['mechanism']}`) to "
          f"{100*hi['oa_rate']:.1f}% (`{hi['mechanism']}`), against "
          f"{100*d['census_oa_rate']:.1f}% for the census as a whole.", ""]
    L += ["**The confound is in the last column and is not controlled here.** "
          "PMC deposition rose steeply over the same period the newer "
          "mechanisms grew, so a mechanism with a recent median year has a "
          "high OA rate for reasons that have nothing to do with its subject. "
          "Read the OA column against the year column, not on its own: this "
          "measures an association, and attributing it to access rather than "
          "to publication era would need a design this page does not have.", ""]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--render-only", action="store_true")
    a = ap.parse_args()
    if a.render_only:
        d = json.loads(OUT_JSON.read_text())
    else:
        d = scan()
        if not d["mechanisms"] or d["with_pmcid"] == 0:
            raise SystemExit(
                "no mechanism matched or no record carries a PMC id, which is "
                "not a finding -- it is what a field-name mismatch looks like.")
        OUT_JSON.write_text(json.dumps(d, indent=1, sort_keys=True) + "\n",
                            encoding="utf-8")
        d = json.loads(OUT_JSON.read_text())
    # Derive BEFORE writing, so the ranks and shifts land in the artifact on
    # both paths. render() derives too and is idempotent; doing it here as well
    # is what makes --render-only refresh a stale artifact rather than only its
    # rendering.
    d = derive(d)
    OUT_JSON.write_text(json.dumps(d, indent=1, sort_keys=True) + "\n",
                        encoding="utf-8")
    OUT_MD.write_text(render(d), encoding="utf-8")
    print(f"wrote {OUT_MD}\nwrote {OUT_JSON}")


if __name__ == "__main__":
    main()
