#!/usr/bin/env python3
"""What the authority filter did to the co-mention layer, pair by pair (#628).

WHY
---
Everything measured so far is either offline prediction or a judged SAMPLE of
mentions. Neither can say what happened to the layer's actual output: which
entity pairs survived, which vanished, and whether the pairs that vanished are
the ones the precision measurement said should.

This compares the rebuilt pair table against the pre-authority baseline
preserved at `corpus/atlas/comention/baseline-preauthority/`. It is the one
measurement that needed the three-hour rebuild.

WHAT IT REPORTS
---------------
* how many distinct pairs survived, by count and by co-mention weight;
* the split by namespace, since the filter is MeSH-only and gene-gene pairs must
  be untouched -- a non-zero gene-gene loss would mean the rule leaked;
* the heaviest pairs lost, with what each side resolves to, so a reader can
  judge whether the losses look like the generic-word failures the filter exists
  to remove;
* the module-support pairs specifically, because that is the layer's only
  consumer and the pre-flight predicted it does not move.

Usage:
    python scripts/comention_rebuild_compare.py
"""

import gzip
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_baseline import atlas_root  # noqa: E402
from config import PROJECT_ROOT  # noqa: E402

OUT = PROJECT_ROOT / "analysis" / "comention-rebuild-compare.md"
RAW = PROJECT_ROOT / "analysis" / "comention-rebuild-compare.json"


def load_pairs(path: Path) -> dict:
    out = {}
    with gzip.open(path, "rt", encoding="utf-8") as fh:
        for line in fh:
            a, b, c = line.rstrip("\n").split("\t")
            out[(a, b)] = int(c)
    return out


def ns(ident: str) -> str:
    return "mesh" if ident.startswith("MESH:") else (
        "omim" if ident.startswith("OMIM:") else "gene")


def main() -> int:
    root = atlas_root()
    new_p = root / "comention" / "pairs.tsv.gz"
    old_p = root / "comention" / "baseline-preauthority" / "pairs.tsv.gz"
    for p in (new_p, old_p):
        if not p.exists():
            print(f"missing {p}", file=sys.stderr)
            return 1

    print("loading pair tables ...", flush=True)
    old, new = load_pairs(old_p), load_pairs(new_p)
    kept = {k: new[k] for k in new if k in old}
    lost = {k: old[k] for k in old if k not in new}
    gained = {k: new[k] for k in new if k not in old}

    def wsum(d):
        return sum(d.values())

    by_ns = {}
    for label, d in (("baseline", old), ("rebuilt", new)):
        for k, c in d.items():
            key = "-".join(sorted((ns(k[0]), ns(k[1]))))
            by_ns.setdefault(key, {"baseline": 0, "rebuilt": 0})[label] += 1

    # Gene-gene pairs are the invariant: the filter is MeSH-only, so any loss
    # there is a leak rather than a design choice.
    gg = by_ns.get("gene-gene", {"baseline": 0, "rebuilt": 0})
    leak = gg["baseline"] - gg["rebuilt"]

    from atlas_graph import load_index
    idx = load_index(root)
    canon = idx.get("canon") or {}
    heavy = sorted(lost.items(), key=lambda kv: -kv[1])[:20]

    L = [
        "# What the authority filter did to the layer (#628)", "",
        "Generated by `scripts/comention_rebuild_compare.py`, comparing the rebuilt",
        "pair table against the pre-authority baseline. Everything measured before",
        "this was either an offline prediction or a judged sample of mentions; this",
        "is the layer's actual output.", "",
        "## Pairs", "",
        "| | baseline | rebuilt | retained |", "|---|---|---|---|",
        f"| distinct pairs | {len(old):,} | {len(new):,} | "
        f"{100*len(new)/max(1,len(old)):.1f}% |",
        f"| co-mention weight | {wsum(old):,} | {wsum(new):,} | "
        f"{100*wsum(new)/max(1,wsum(old)):.1f}% |",
        f"| pairs lost | | {len(lost):,} | |",
        f"| pairs gained | | {len(gained):,} | |", "",
    ]
    if gained:
        L += [
            f"**{len(gained):,} pairs are NEW**, which a purely subtractive filter",
            "could not produce. Removing a long alias unmasks a shorter surviving one",
            "at the same position, because the matcher is longest-match with",
            "consumption. The pre-flight predicted this on 400 sentences and it holds",
            "at corpus scale.", "",
        ]
    L += [
        "## By namespace, and the invariant that matters", "",
        "| pair type | baseline | rebuilt | retained |", "|---|---|---|---|",
    ]
    for k in sorted(by_ns, key=lambda k: -by_ns[k]["baseline"]):
        v = by_ns[k]
        L.append(f"| {k} | {v['baseline']:,} | {v['rebuilt']:,} | "
                 f"{100*v['rebuilt']/max(1,v['baseline']):.1f}% |")
    L += [
        "",
        f"**Gene-gene pairs: {gg['baseline']:,} -> {gg['rebuilt']:,}"
        + ("**, unchanged, as a MeSH-only rule requires."
           if leak == 0 else
           f", a loss of {leak:,}.** That should be zero -- the rule is MeSH-only, "
           "so any gene-gene loss is a leak and must be explained before this "
           "layer is trusted."), "",
        "## The heaviest pairs the filter removed", "",
        "| pair | co-mentions |", "|---|---|",
    ]
    for (a, b), c in heavy:
        L.append(f"| {canon.get(a, a)} — {canon.get(b, b)} | {c:,} |")
    L += [
        "", "Read these as the test of whether the filter removed what it was",
        "supposed to. A generic word resolving to a specific descriptor is the",
        "failure mode it exists for; a real entity pair appearing here is a cost,",
        "and the two are told apart by reading, not by the count.", "",
        "## Limits", "",
        "* Pairs, not mentions. A pair survives if ANY sentence still names both",
        "  entities, so pair retention overstates mention retention.",
        "* This says what changed, not whether what changed was right. Precision on",
        "  the rebuilt layer needs a fresh judged sample "
        "(`scripts/comention_judge_prep.py`).",
    ]
    OUT.write_text("\n".join(L) + "\n")
    RAW.write_text(json.dumps({
        "baseline_pairs": len(old), "rebuilt_pairs": len(new),
        "lost": len(lost), "gained": len(gained),
        "baseline_weight": wsum(old), "rebuilt_weight": wsum(new),
        "by_namespace": by_ns, "gene_gene_leak": leak,
    }, indent=2) + "\n")
    print(f"pairs {len(old):,} -> {len(new):,} ({100*len(new)/max(1,len(old)):.1f}%), "
          f"gene-gene leak {leak}")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
