#!/usr/bin/env python3
"""Measure how much cancer full text is obtainable, and under what terms.

MISSION.md said "roughly 21% of cancer articles are in PMC open access; the
remainder is paywalled". The first half is right. The second half is not: a
substantial slice of the remainder is freely readable without being in PMC, and
-- separately -- a slice of it is openly licensed while flagged OPEN_ACCESS:N.

Three DIFFERENT questions get three different numbers, and the reason to
compute them separately is that the honest ceiling depends on which one you
mean:

  IN PMC OA      -- in the PMC open-access subset. The old 21%.
  READABLE       -- Europe PMC holds the text (inEPMC=Y) or flags it OA. What
                    a reader can reach without paying.
  REDISTRIBUTABLE-- carries an explicitly open licence. What this project may
                    republish. Strictly the smallest of the three.

Counts come from Europe PMC's own hitCount, so each is that service's answer to
a stated query rather than an estimate of ours. Output: analysis/fulltext-ceiling.{md,json}
"""
from __future__ import annotations

import json
import time
from datetime import datetime, timezone
import urllib.parse
import urllib.request
from pathlib import Path

API = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"
ROOT = Path(__file__).resolve().parent.parent

# Named the way the artifact-freshness harness discovers generators, so this
# script appears in that inventory. It cannot be regenerate-and-diff gated --
# its input is a live API whose counts move daily -- but being DISCOVERED and
# then explicitly exempted is different from being invisible to the gate
# because it happened not to declare these two constants.
OUT_MD = ROOT / "analysis/europepmc-access-ceiling.md"
OUT_JSON = ROOT / "analysis/europepmc-access-ceiling.json"

# Each entry is (label, query, what the number MEANS). The queries are the
# definitions -- there is no post-hoc adjustment applied to any of them.
QUERIES = [
    ("all_cancer", "cancer",
     "Every Europe PMC record matching cancer. The denominator."),
    ("in_pmc_oa", "cancer AND OPEN_ACCESS:Y",
     "In Europe PMC's open-access subset. This is the figure MISSION.md quoted."),
    ("readable", "cancer AND (IN_EPMC:Y OR OPEN_ACCESS:Y)",
     "Europe PMC holds the full text. Free to read; says nothing about reuse."),
    ("open_licence", "cancer AND (LICENSE:cc0 OR LICENSE:'cc by' OR LICENSE:'cc-by' "
                     "OR LICENSE:'cc by-sa' OR LICENSE:'public domain')",
     "Carries a licence permitting redistribution with attribution."),
    ("open_licence_not_oa_flagged", "cancer AND (LICENSE:'cc by' OR LICENSE:'cc-by' OR LICENSE:cc0) "
                                    "AND OPEN_ACCESS:N",
     "Openly licensed BUT flagged OPEN_ACCESS:N -- collectable, and invisible "
     "to any filter that trusts the flag alone."),
    ("readable_not_in_pmc_oa", "cancer AND IN_EPMC:Y AND OPEN_ACCESS:N",
     "Readable in Europe PMC yet outside the OA subset. The concrete "
     "counterexample to 'the remainder is paywalled'."),
]


def hits(query: str) -> int:
    url = f"{API}?{urllib.parse.urlencode({'query': query, 'format': 'json', 'pageSize': 1})}"
    req = urllib.request.Request(url, headers={"User-Agent": "cancer-research-atlas/1.0"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return int(json.load(r)["hitCount"])


def main() -> int:
    out = {}
    for key, q, meaning in QUERIES:
        n = hits(q)
        out[key] = {"count": n, "query": q, "means": meaning}
        print(f"  {key:28s} {n:>12,}")
        time.sleep(0.34)

    total = out["all_cancer"]["count"]
    for k, v in out.items():
        v["pct_of_all"] = round(100 * v["count"] / total, 2) if total else None

    OUT_JSON.write_text(json.dumps(out, indent=2) + "\n")
    OUT_MD.write_text(render(out))
    print("\nwrote analysis/europepmc-access-ceiling.{md,json}")
    return 0


def render(out: dict) -> str:
    total = out["all_cancer"]["count"]

    def row(k):
        v = out[k]
        return f"| `{k}` | {v['count']:,} | {v['pct_of_all']}% | {v['means']} |"

    md = [
        "# What Europe PMC will let us read, and what it will let us republish",
        "",
        "Generated by `scripts/fulltext_ceiling.py`. Every count is Europe PMC's",
        "own `hitCount` for the query shown; nothing here is adjusted or estimated.",
        "",
        f"**Measured {datetime.now(timezone.utc).strftime('%Y-%m-%d')}.** Europe PMC grows daily, so",
        "these are a reading taken on that date rather than fixed constants. The",
        "*relationships* between the buckets are the durable part; re-run the script",
        "for current absolute counts.",
        "",
        "| bucket | records | share of all cancer records | what it means |",
        "|---|---:|---:|---|",
        *(row(k) for k, _, _ in QUERIES),
        "",
        "## Why three numbers instead of one",
        "",
        "**Readable is not redistributable.** A paper free to read on a publisher's",
        "site with no licence attached (\"bronze\" open access) can be read by anyone",
        "and republished by no one. Any single percentage for \"how much full text can",
        "we get\" silently picks one of these and hides the other.",
        "",
        "**The open-access flag is not a licence.** `OPEN_ACCESS:Y` means \"in Europe",
        f"PMC's OA subset\". {out['open_licence_not_oa_flagged']['count']:,} cancer records carry CC BY or CC0",
        "while flagged `OPEN_ACCESS:N` -- openly licensed, and invisible to any",
        "collection filter that trusts the flag alone.",
        "",
        "**Availability is not permission.** Whether Europe PMC *holds* a text and",
        "whether we *may take* it are independent, and a collector must ask both:",
        "asking for text that is permitted but not held returns 404 once per record.",
        "",
        "## Not the same measurement as `census-fulltext-ceiling.md`",
        "",
        "That page asks a different question over a different population: how",
        "many CENSUS records carry a PMC identifier, bucketed by study design,",
        "in order to bound what reading full text could fix about the design-label",
        "gap. It is the source of the ~21% figure quoted in MISSION.md.",
        "",
        "This page asks what Europe PMC will serve and under what licence, in",
        "order to bound what a COLLECTOR can legitimately take. The two numbers",
        "are close enough to be mistaken for each other and are not comparable:",
        "different denominators, different definitions of reachable. Neither",
        "supersedes the other.",
        "",
        "## Which denominator these percentages use",
        "",
        f"All shares above are of Europe PMC's own free-text `cancer` set ({total:,}",
        "records). That is NOT this project's census, which is defined by the MeSH",
        "C04 neoplasms tree and counts ~5.19M. The two sets overlap heavily but are",
        "built by different rules -- a free-text match catches papers that merely",
        "mention cancer, and misses indexed papers that never use the word. So these",
        "percentages describe Europe PMC, and are not interchangeable with a",
        "percentage computed over the census.",
        "",
        "## What this corrects",
        "",
        "MISSION.md said roughly 21% of cancer articles are in PMC open access and",
        "that **the remainder is paywalled**. The second clause is what this",
        "measurement refutes, and it does so independently of which denominator you",
        f"prefer: {out['readable_not_in_pmc_oa']['count']:,} cancer records are readable in Europe PMC while",
        "flagged `OPEN_ACCESS:N`. Whatever share of the whole that is, it is a large",
        "population that is neither in the OA subset nor behind a paywall, so the",
        "remainder is not uniformly paywalled.",
        "",
        "The 21% figure itself is left alone here rather than restated. It was",
        f"computed over the census; the nearest number this script measures ({out['in_pmc_oa']['pct_of_all']}%)",
        "is computed over a different and larger set, and quoting one as",
        "confirmation of the other would be comparing two different questions.",
        "",
        "The redistribution clause is untouched and reinforced: only",
        f"{out['open_licence']['pct_of_all']}% carries a licence permitting republication, against",
        f"{out['readable']['pct_of_all']}% merely readable. Roughly two thirds of what can be read",
        "here cannot be republished by us.",
        "",
    ]
    return "\n".join(md)


if __name__ == "__main__":
    raise SystemExit(main())
