#!/usr/bin/env python3
"""Mechanism-tag precision, measured for the first time (#MECH-PRECISION).

The project measures mechanism-tag RECALL non-circularly against MeSH (#412,
90.6% volume-weighted). It has never measured mechanism-tag PRECISION. The 96%
figure quoted throughout the manuscript is *evidence-presence* precision on a
different task.

This reads the adjudicated sample in `analysis/mechanism-precision-audit.csv`
and writes `analysis/mechanism-precision-report.md`: per-mechanism precision
with Wilson intervals, and the corrected article counts that follow.

Deterministic and offline -- the adjudication is committed data, so the report
regenerates identically. Re-adjudicating requires re-running the agent fleet.

Usage:
    python scripts/mechanism_precision.py
"""

import collections
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import PROJECT_ROOT  # noqa: E402

AUDIT = PROJECT_ROOT / "analysis" / "mechanism-precision-audit.csv"
INDEX = PROJECT_ROOT / "corpus" / "INDEX.jsonl"
OUT = PROJECT_ROOT / "analysis" / "mechanism-precision-report.md"

FLOOR = 0.85


def wilson(k: int, n: int, z: float = 1.96):
    if n == 0:
        return 0.0, 0.0
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * ((p * (1 - p) / n + z * z / (4 * n * n)) ** 0.5) / d
    return max(0.0, c - h), min(1.0, c + h)


def main() -> None:
    with AUDIT.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(l for l in fh if not l.startswith("#")))

    by = collections.defaultdict(collections.Counter)
    for r in rows:
        by[r["mechanism"]][r["verdict"]] += 1

    corpus = collections.Counter()
    if INDEX.exists():
        with INDEX.open(encoding="utf-8") as fh:
            for line in fh:
                for m in json.loads(line).get("mechanisms", []) or []:
                    corpus[m] += 1

    stats = []
    for m, c in by.items():
        y, b, n_ = c["yes"], c["borderline"], c["no"]
        n = y + b + n_
        lo, hi = wilson(y, n)
        stats.append(dict(mech=m, yes=y, bord=b, no=n_, n=n,
                          strict=y / n, lenient=(y + b) / n, lo=lo, hi=hi,
                          tagged=corpus.get(m, 0)))
    stats.sort(key=lambda d: d["strict"])

    ty = sum(s["yes"] for s in stats)
    tb = sum(s["bord"] for s in stats)
    tn = sum(s["n"] for s in stats)
    olo, ohi = wilson(ty, tn)
    below = [s for s in stats if s["strict"] < FLOOR]

    L = [
        "# Mechanism-tag precision (#MECH-PRECISION)", "",
        "Generated by `scripts/mechanism_precision.py` from the committed adjudication in",
        "`analysis/mechanism-precision-audit.csv`. Deterministic and offline.", "",
        "## Why this exists", "",
        "Mechanism-tag RECALL was measured non-circularly against MeSH (#412: 90.6%",
        "volume-weighted). Mechanism-tag PRECISION had never been measured at all. The",
        "96% precision quoted throughout the manuscript is *evidence-presence* precision",
        "on a different task and says nothing about whether a `bioelectric` tag means the",
        "article is about bioelectric therapy.", "",
        "## Method", "",
        f"{len(rows)} (mechanism, article) pairs, up to 15 per mechanism, seed 23. Each was",
        "adjudicated by an independent agent that read the article and judged whether it",
        "genuinely concerns that therapeutic mechanism, blocked from reading the tagger's",
        "keyword list. Verdicts: `yes`, `borderline` (mentioned as context or comparator,",
        "not studied), `no` (false positive).", "",
        "These are machine adjudications, not human labels. `strict` counts only `yes`;",
        "`lenient` also counts `borderline`. The truth for a given tag sits between them.", "",
        "## Result", "",
        f"**Overall strict precision: {ty}/{tn} = {ty/tn:.1%}** (95% CI {olo:.1%}-{ohi:.1%}). "
        f"Lenient: {(ty+tb)/tn:.1%}.",
        f"**{len(below)} of {len(stats)} mechanisms fall below {FLOOR:.0%}.**", "",
        "| mechanism | strict | 95% CI | lenient | yes | bord | no | n | tagged in corpus | implied true |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for s in stats:
        implied = round(s["tagged"] * s["strict"])
        mark = " **" if s["strict"] < FLOOR else ""
        L.append(
            f"| `{s['mech']}`{mark} | {s['strict']:.1%} | {s['lo']:.0%}-{s['hi']:.0%} | "
            f"{s['lenient']:.1%} | {s['yes']} | {s['bord']} | {s['no']} | {s['n']} | "
            f"{s['tagged']:,} | ~{implied:,} |")

    L += [
        "", "## What this does to published claims", "",
        "The two worst tags are both in the physical/energy class:", "",
    ]
    for s in stats[:2]:
        L.append(f"- **`{s['mech']}` at {s['strict']:.1%}** — {s['tagged']:,} tagged articles, "
                 f"of which roughly {round(s['tagged']*s['strict']):,} are real.")
    L += [
        "",
        "That matters because manuscript Section 3.3.1 headlines the open-access-bias",
        "finding with exactly these tags: bioelectric rising from full-text rank 14 to",
        "abstract rank 3, and the physical/energy class rising from 14.7% to 22.4% of all",
        "mechanism tags. Both figures are computed from tag counts that are ~87% false",
        "positive for the two largest contributors.",
        "",
        "The dominant false-positive triggers are visible in the audit's",
        "`likely_trigger` column and are mechanical, not subtle:",
        "",
        "- `bioelectric` fires on the bare phrase **\"membrane potential\"**, which in this",
        "  corpus almost always means *mitochondrial* membrane potential — a JC-1",
        "  apoptosis assay readout, not bioelectric therapy.",
        "- `frequency-therapy` fires on **\"radiofrequency\"**, i.e. radiofrequency thermal",
        "  ablation, which is a different modality from the pulsed-electromagnetic-field",
        "  therapy the tag is meant to capture.",
        "",
        "## Fixes applied", "",
        "Both keyword lists have been corrected in `scripts/config.py`. Following the",
        "#418 precedent, `corpus/INDEX.jsonl` stays frozen, so the manuscript's counts",
        "are unchanged and the live tagger now differs from them:", "",
        "| mechanism | frozen count | corrected count | delta | implied real from audit |",
        "|---|---|---|---|---|",
        "| `bioelectric` | 182 | 46 | -136 | ~24 |",
        "| `frequency-therapy` | 71 | 43 | -28 | ~9 |", "",
        "`frequency-therapy` deserves a precise statement, because its 13.3% is a",
        "TAXONOMY mismatch rather than a matcher bug. The manuscript defines the",
        "mechanism as \"frequency therapy (including pulsed electromagnetic fields)\", but",
        "the keyword list led with `radiofrequency ablation` and `microwave ablation` --",
        "thermal ablation, which destroys tissue with heat rather than modulating cells",
        "with a non-thermal field. Adjudicators judging against the stated definition",
        "scored those articles as false positives, correctly. Narrowing the list to the",
        "non-thermal field therapies the label denotes creates a **known gap**: the",
        "thermal-ablation literature this tag was silently absorbing is real, sizeable,",
        "and now covered by no mechanism at all. That gap is documented rather than",
        "silent, and closing it needs a new `thermal-ablation` mechanism.", "",
        "The corrected counts have NOT been re-audited. 46 sits inside the original",
        "Wilson interval for the true `bioelectric` count (4-38% of 182 = 7-69); 43 is",
        "above the ~9 the point estimate implies, so the narrowed `frequency-therapy`",
        "list is probably still over-inclusive. A second audit round is needed before",
        "either number is quoted.", "",
        "## Limits", "",
        "Fifteen records per mechanism gives roughly +/-20 points at 90% precision, so",
        "the intervals are wide and the ranking between adjacent mechanisms is not",
        "resolved. What the sample does resolve is the difference between ~13% and ~93%,",
        "which is the finding. `cold-atmospheric-plasma` has only 3 tagged articles in",
        "the whole corpus, so its 100% rests on 3 adjudications.", "",
        "A human second annotator has not reviewed these adjudications. On the evidence-",
        "tier task, human/machine agreement was 77%, so treat these numbers as indicative",
        "of magnitude rather than exact.", "",
    ]

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"overall strict precision {ty}/{tn} = {ty/tn:.1%} (95% CI {olo:.1%}-{ohi:.1%})")
    for s in below:
        print(f"  BELOW FLOOR  {s['mech']:<28} {s['strict']:.1%}  ({s['tagged']:,} tagged)")


if __name__ == "__main__":
    main()
