#!/usr/bin/env python3
"""Every applicable treatment arm, on the same tumour, read side by side.

WHY THIS EXISTS
---------------
`analysis/modality-coverage.md` measured this project's central criticism and
then measured it away: the engine went from thirteen of sixteen taxonomy
mechanisms with NO representation to none. What that left was a harder
question, which the report now leads with -- **presence is not applicability**.

This is the page where applicability stops being a count and becomes a
number. `sim-modality-panel` runs every `Treatment` variant against the
identical tumour from the identical seed, so a difference between two rows is
the arm and nothing else.

WHAT THIS IS NOT, and it is stated first because the table invites the error
-----------------------------------------------------------------------------
**Not a ranking of therapies.** Each arm's kill fraction is a function of the
parameters it was given, and for every arm except radiation's DNA channel
those parameters are placeholders. `CALIBRATION_STATUS.md` carries a row per
layer and most read `used in any reported number: N` precisely because they
are uncalibrated. A reader who takes the ordering here as clinical is reading
the wrong artifact, and the calibration column is printed on every row so that
reading is hard to sustain.

What the panel DOES show is structural, and structure is what this engine can
honestly report: which arms need ferroptotic death and which do not, which are
dose-responses and which are thresholds, and which are limited by DELIVERY
rather than by biology. Those are comparisons between MECHANISMS under one
model.

Offline: reads the binary's committed JSON.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PANEL = REPO / "simulations" / "output" / "modality-panel" / "modality_panel.json"
OUT_MD = REPO / "analysis" / "modality-panel.md"
OUT_JSON = REPO / "analysis" / "modality-panel.json"


def scan() -> dict:
    if not PANEL.exists():
        raise SystemExit(
            f"{PANEL} not found -- run `cargo run --release -p sim-modality-panel`")
    return json.loads(PANEL.read_text())


def assemble(raw: dict) -> dict:
    arms = sorted(raw["arms"], key=lambda a: -a["kill_fraction"])
    ferro = [a for a in arms if "ferroptosis engine" in a["route"]]
    non_ferro = [a for a in arms if "ferroptosis engine" not in a["route"]]
    return dict(raw, arms=arms,
                n_arms=len(arms),
                n_ferroptosis_routed=len(ferro),
                n_other_routes=len(non_ferro),
                distinct_routes=sorted({a["route"] for a in arms}))


def render(d: dict) -> str:
    arms = d["arms"]
    by = {a["arm"]: a for a in arms}
    L = ["# Every applicable treatment arm, on the same tumour", "",
         "*Generated by `scripts/modality_panel_report.py --render-only` from "
         "`sim-modality-panel`. Offline; reads the binary's committed JSON.*",
         "",
         f"{d['n_cells']:,} cells per arm, seed {d['seed']}. Every arm sees "
         "the SAME tumour from the SAME seed, so a difference between two rows "
         "is the arm and nothing else.", "",
         "| arm | kill | what kills | what limits it | calibration |",
         "|---|--:|---|---|---|"]
    for a in arms:
        L.append(f"| {a['arm']} | {a['kill_fraction'] * 100:.2f}% | "
                 f"{a['route']} | {a['limited_by']} | {a['calibration']} |")
    L += ["",
          f"**{d['n_arms']} arms, {len(d['distinct_routes'])} distinct routes "
          f"to death**, and only {d['n_ferroptosis_routed']} of them go through "
          "the ferroptosis engine. That is the number this whole campaign was "
          "about: a reader who opened this repository a month ago would have "
          "found one route and four arms.", ""]

    adc, sdt = by.get("AntibodyDrugConjugate"), by.get("SDT")
    if adc and sdt:
        ratio = sdt["kill_fraction"] / adc["kill_fraction"] if adc["kill_fraction"] else float("inf")
        L += ["## The sharpest row is the one about delivery", "",
              f"`AntibodyDrugConjugate` kills {adc['kill_fraction'] * 100:.2f}% "
              f"against `SDT`'s {sdt['kill_fraction'] * 100:.2f}% — a factor of "
              f"{ratio:.0f} — **and they share the payload's pharmacology "
              "exactly**. The ADC arm runs the same ferroptosis engine with the "
              "same parameters; what differs is that the payload arrives on a "
              "~150 kDa antibody, and the binding-site barrier holds its "
              "penetration to about 7 µm.", "",
              "This project has argued since Chapter 6 that delivery dominates "
              "the in-vitro-to-in-vivo gap. This is the first row in the "
              "repository where the SAME pharmacology is run through two "
              "delivery routes and the gap is the only difference between "
              "them.", ""]

    sdt_v, pdt_v = by.get("SDT"), by.get("PDT")
    if sdt_v and pdt_v and abs(sdt_v["kill_fraction"] - pdt_v["kill_fraction"]) < 1e-9:
        L += ["## Two rows are identical, and that is a property of the panel", "",
              "`SDT` and `PDT` report the same figure to the last digit. They "
              "are not the same modality — the entire physical-modality "
              "argument of this manuscript turns on light dying in "
              "millimetres while ultrasound reaches centimetres — but this "
              "panel is DEPTH-FREE, and their exogenous-ROS parameters are "
              "equal by default. Strip the depth away and the two arms are the "
              "same arm.", "",
              "That is worth stating rather than hiding, because it says "
              "exactly what this table can and cannot see: it compares "
              "MECHANISMS, and the thing that separates SDT from PDT is not a "
              "mechanism but a geometry. `analysis/depth-reach-comparison.md` "
              "is where that difference lives.", ""]

    ab = d.get("adoptive_barriers")
    if ab:
        # Every factor below is DERIVED and the three must multiply to the
        # collapse, because a reviewer set the antigen fraction to 1e-9 and the
        # page went on saying the ceiling "does not bind" while the headline
        # moved by three orders of magnitude and the decomposition beside it
        # did not move at all. Prose about a computed quantity has to be
        # computed, and the reconciliation is asserted here rather than trusted.
        collapse = ab["leukaemia_kill_fraction"] / ab["solid_tumour_kill_fraction"]
        delivery_x = 1.0 / ab["delivery_efficiency_solid"]
        persist_x = 1.0 / ab["persistence_at_run_end_solid"]
        # `ceiling_x` was computed as `collapse / (delivery * persistence)`,
        # which is a RESIDUAL: it absorbed whatever the other two did not
        # explain and then labelled it "antigen ceiling", so "the factors
        # multiply to the collapse" was true by construction and unfalsifiable.
        # `antigen_ceiling_solid` was sitting in the JSON unread. A reviewer
        # pushed the leukaemia arm into its kill cap and the page printed an
        # antigen ceiling of 0.4x -- a ceiling that multiplies kills UP -- one
        # line above prose asserting it was exactly 1x.
        # The ceiling is a CAP: it contributes only if it FIRES. Dividing by
        # the antigen fraction unconditionally reported 1.2x for a cap that
        # never bound and left the product 1.25x away from the collapse it
        # claimed to decompose. Both quantities come from the binary now.
        ceiling_x = (ab["solid_tumour_kill_fraction_before_ceiling"]
                     / ab["solid_tumour_kill_fraction"])
        product = delivery_x * persist_x * ceiling_x
        residual = product / collapse
        binds = ceiling_x > 1.01
        L += ["## One construct, two diseases", "",
              "The adoptive row above is the LEUKAEMIA setting, and on its own "
              "it describes the indication these therapies were approved for "
              "rather than the setting this engine simulates. Run the "
              "identical infusion through the three barriers PMID 31848460 "
              "names — trafficking to, infiltration into and activation "
              "within the tumour — and then through the antigen ceiling:", "",
              "| | kill fraction |", "|---|--:|",
              f"| leukaemia (every barrier open) | {ab['leukaemia_kill_fraction']:.4%} |",
              f"| solid tumour | {ab['solid_tumour_kill_fraction']:.6%} |", "",
              f"**A {collapse:,.0f}-fold collapse from the same construct.** "
              "Each factor below is read from the barrier it names, and their "
              f"product is {product:,.0f}x — "
              + (f"which is the collapse, so the decomposition is complete."
                 if abs(residual - 1.0) < 0.01 else
                 f"**{residual:.2f}x away from the collapse, so something "
                 "outside these three barriers is acting and this "
                 "decomposition is INCOMPLETE.** The gap is reported rather "
                 "than absorbed into one of the factors, which is what an "
                 "earlier version did.") + "", "",
              "| step | factor |", "|---|--:|",
              f"| delivery (the three barriers) | {delivery_x:.1f}x |",
              f"| persistence over the run | {persist_x:.1f}x |",
              f"| antigen ceiling | {ceiling_x:.1f}x |", "",
              ("**The antigen ceiling binds here** and is part of the collapse."
               if binds else
               "**The antigen ceiling does not bind here** — it contributes "
               "exactly 1x, because delivery and persistence have already "
               "taken the kill far below it. That is derived from the numbers "
               "above rather than stated: if the cap were reached, the third "
               "row would exceed 1 and this sentence would say so.") +
              " It is a wall rather than a coefficient either way, so a larger "
              "infusion cannot climb it — which is the asymmetry with the ADC, "
              "whose cleavable payload kills antigen-negative neighbours and "
              "passes it.", "",
              "**Every barrier value is an uncalibrated placeholder and the "
              "figures above inherit that.** What the corpus establishes is "
              "that the barriers are real and GENERAL rather than "
              "antigen-specific; it does not establish which dominates, so "
              "the decomposition is a property of the preset and not a "
              "finding. The direction — that the same construct can fail "
              "without any single step looking catastrophic — is what "
              "survives.", ""]
    L += ["## What this does not say", "",
          "**It is not a ranking of therapies.** Every kill fraction is a "
          "function of the parameters the arm was given, and for every arm "
          "except radiation's DNA channel those are placeholders. The "
          "calibration column is printed on every row for that reason, and "
          "`simulations/calibration/CALIBRATION_STATUS.md` carries the full "
          "accounting — most rows read `used in any reported number: N`.", "",
          "**The immune arms are shown at an antigenicity this binary "
          "supplies.** The engine's default is zero, which would make "
          "checkpoint blockade kill nothing at all; that default is deliberate "
          "and is what keeps every committed number unmoved. The value used "
          f"here ({d['inputs']['baseline_antigenicity']}) is an INPUT, "
          "recorded in the JSON, not a fitted quantity.", "",
          "**Ablation's row is a margin, not a dose.** It is the covered "
          "fraction, because above threshold everything inside dies and "
          "nothing outside does. Reading it beside a dose-response row as "
          "though both were efficacies is the error the `what kills` column "
          "exists to prevent.", ""]
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--render-only", action="store_true")
    a = ap.parse_args()
    d = assemble(json.loads(OUT_JSON.read_text()) if a.render_only else scan())
    OUT_JSON.write_text(json.dumps(d, indent=1) + "\n")
    OUT_MD.write_text(render(d))
    print(f"wrote {OUT_MD}")
    print(f"wrote {OUT_JSON}")
    print(f"  {d['n_arms']} arms, {len(d['distinct_routes'])} distinct routes, "
          f"{d['n_ferroptosis_routed']} through the ferroptosis engine")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
