"""How each treatment arm fares under the tumour microenvironment.

WHY THIS IS THE DEEP QUESTION
-----------------------------
`analysis/modality-panel.md` answers "what does each arm do to a naive
tumour". That is the shallow question and the one a reader over-interprets.
This project's actual contribution has never been kill fractions: it is the
three RESISTANCE AXES the ferroptosis chapters establish -- hypoxia, stromal
shielding and acidic pH -- and the finding that pharmacologic and physical
modalities respond to them differently.

Every arm the coverage campaign added was untested against those axes, which
is precisely the gap between "the engine can express it" and "the engine has
something to say about it". This page closes it, and reports the two axes
where it does not.

THE AXES ARE APPLIED THROUGH THE SAME HELPERS
---------------------------------------------
Hypoxia scales exogenous-ROS yield and radiation's delivered dose through the
identical Alper-Howard-Flanders hyperbola; stroma raises the antioxidant
setpoint; acidic pH traps weak bases outside the cell. No arm gets a
mechanism-specific fudge, because a modality comparison only means anything
if the environment is identical.

Offline: reads the binary's committed sweep JSON.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SWEEP = REPO / "simulations" / "output" / "modality-panel" / "modality_tme_sweep.json"
OUT_MD = REPO / "analysis" / "modality-tme.md"
OUT_JSON = REPO / "analysis" / "modality-tme.json"

# An axis whose worst-case relative effect is below this on EVERY arm is
# reported INERT rather than quietly listed with tiny numbers. A table of
# 0.08% differences invites a reader to believe an axis was tested when the
# configuration could not see it.
INERT_THRESHOLD = 0.02


def scan() -> dict:
    if not SWEEP.exists():
        raise SystemExit(
            f"{SWEEP} not found -- run "
            "`cargo run --release -p sim-modality-panel -- --tme-sweep`")
    return json.loads(SWEEP.read_text())


def _effect(conds, arm, axis):
    """Largest relative change in `arm` attributable to `axis` alone.

    Paired: every ON condition is compared with the OFF condition identical in
    the other two axes, so an effect cannot be manufactured by an axis that
    happens to co-vary.
    """
    worst = 0.0
    for on in [c for c in conds if c[axis]]:
        off = next((c for c in conds
                    if not c[axis]
                    and all(c[k] == on[k] for k in ("hypoxic", "stroma", "acidic")
                            if k != axis)), None)
        if off is None:
            continue
        base = off["arms"].get(arm)
        got = on["arms"].get(arm)
        if base is None or got is None or base <= 0:
            continue
        worst = max(worst, abs(base - got) / base)
    return worst


def assemble(raw: dict) -> dict:
    conds = raw["conditions"]
    arms = sorted({a for c in conds for a in c["arms"]})
    axes = [("hypoxic", "hypoxia"), ("stroma", "stromal shielding"),
            ("acidic", "acidic pH")]
    effects = {label: {a: _effect(conds, a, key) for a in arms}
               for key, label in axes}
    inert = [label for _, label in axes
             if max(effects[label].values(), default=0.0) < INERT_THRESHOLD]
    live = [label for _, label in axes if label not in inert]
    # Robustness ordering under the axes that actually bite.
    order = sorted(
        arms, key=lambda a: max((effects[l][a] for l in live), default=0.0))
    return dict(raw, arms=arms, effects=effects, inert_axes=inert,
                live_axes=live, robustness_order=order,
                inert_threshold=INERT_THRESHOLD)


def render(d: dict) -> str:
    conds = d["conditions"]
    arms = d["arms"]
    L = ["# How each arm fares under the tumour microenvironment", "",
         "*Generated by `scripts/modality_tme_report.py --render-only` from "
         "`sim-modality-panel --tme-sweep`. Offline; reads the binary's "
         "committed sweep.*", "",
         "The head-to-head panel asks what each arm does to a NAIVE tumour. "
         "This asks the question this project actually exists to ask: what "
         "the tumour microenvironment does to it. Every axis is applied "
         "through the same helpers the ferroptosis chapters use, so no arm "
         "gets a mechanism-specific adjustment.", "",
         "| condition | " + " | ".join(arms) + " |",
         "|---|" + "--:|" * len(arms)]
    for c in conds:
        lbl = ("hypoxic" if c["hypoxic"] else "normoxic")
        if c["stroma"]:
            lbl += " + stroma"
        if c["acidic"]:
            lbl += " + acid"
        L.append(f"| {lbl} | "
                 + " | ".join(f"{c['arms'][a] * 100:.2f}%" for a in arms) + " |")

    live, inert = d["live_axes"], d["inert_axes"]
    L += ["", "## One axis discriminates, and two cannot be seen here", ""]
    if live:
        L += [f"**{', '.join(live)}** separates the arms, and the ordering it "
              "produces is the finding — largest relative loss first:", ""]
        rows = sorted(arms,
                      key=lambda a: -max(d["effects"][l][a] for l in live))
        for a in rows:
            worst = max(d["effects"][l][a] for l in live)
            L.append(f"* `{a}` — loses {worst * 100:.0f}% of its kill")
        L += ["", "That ordering was not tuned for. It follows from the "
              "mechanisms: an arm whose lethality depends on oxygen loses "
              "most, an arm whose dose is merely modified by oxygen loses "
              "less, and a threshold arm loses nothing because a destroyed "
              "cell does not care what its oxygen tension was.", ""]

    if inert:
        L += [f"**{', '.join(inert)} are INERT in this configuration**, "
              f"moving every arm by less than {d['inert_threshold'] * 100:.0f}%, "
              "and that is reported rather than listed as a row of tiny "
              "numbers — a table of 0.08% differences invites a reader to "
              "believe an axis was tested when the configuration could not "
              "see it.", "",
              "The reasons are specific and both are limits of THIS panel "
              "rather than of the axes:", "",
              "* **Acidic pH** acts by trapping weak bases outside the cell, "
              "so it scales what a delivered drug achieves. The delivered arm "
              "here kills essentially nothing at baseline, so there is "
              "nothing for the trapping to scale. The axis is real and its "
              "effect is measured in the spatial model "
              "(`analysis/` pH work); a single-cell panel at default "
              "parameters cannot show it.", "",
              "* **Stromal shielding** raises the antioxidant setpoint, which "
              "matters when the insult is close to the cell's repair "
              "capacity. The exogenous-ROS arms here overwhelm it by an order "
              "of magnitude, so raising the buffer changes almost nothing. "
              "The stromal chapter measures this axis where it bites — at the "
              "tumour margin, against a pharmacologic inducer.", ""]

    L += ["## What this does not say", "",
          "**Two of the three axes were not tested, they were not visible.** "
          "That is a weaker statement than 'these arms are robust to stroma "
          "and pH' and it is the true one. An arm can only be shown resistant "
          "to a pressure the configuration can apply.", "",
          "**The immune arm's hypoxia response is a PREDICTION, not a "
          "measurement.** Oxygen does not enter its kill term; what changes "
          "is the suppressor field it meets, and that coupling is asserted by "
          "the model rather than fitted. A redirected T cell does not need "
          "oxygen to lyse a target, which is why the arm loses less than the "
          "ROS arms and more than ablation.", "",
          "**Ablation's flat row is the model being consistent, not a "
          "result.** A threshold arm is unaffected by every axis here by "
          "construction. Reporting it as robustness would be circular; it is "
          "in the table because leaving it out would make the other rows look "
          "like a full account of the space.", "",
          "**Every magnitude is uncalibrated** except radiation's DNA "
          "channel. `simulations/calibration/CALIBRATION_STATUS.md` carries "
          "the accounting; the ORDERING is the result, and the numbers are "
          "not.", ""]
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--render-only", action="store_true")
    a = ap.parse_args()
    d = assemble(json.loads(OUT_JSON.read_text()) if a.render_only else scan())
    OUT_JSON.write_text(json.dumps(d, indent=1) + "\n")
    OUT_MD.write_text(render(d))
    print(f"wrote {OUT_MD}")
    print(f"wrote {OUT_JSON}")
    print(f"  live axes: {d['live_axes']}  inert: {d['inert_axes']}")
    for a_ in d["robustness_order"]:
        worst = max((d["effects"][l][a_] for l in d["live_axes"]), default=0.0)
        print(f"    {a_:22s} worst relative loss {worst * 100:5.1f}%")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
