#!/usr/bin/env python3
"""Do the news pipeline's "verified" PMIDs support the claims? (#NEWS-VERIFY)

WHY
---
`news/NEWS_INDEX.jsonl` marks 44 claims `verification_status: "verified"` and
attaches `linked_pmids` as the evidence. Two of those links reached the
manuscript as footnotes reading *"Verified: PMID:X"*.

They do not survive being looked at. The claim about electric fields and brain
cancer is "verified" against five papers on freshwater fish biodiversity,
school vision programs, printable colouration, post-vaccine inflammation, and a
survey of speech-language pathologists. Not one concerns electric fields, brain
tumours, or immunotherapy.

The pattern says what happened: the linked identifiers cluster in a narrow
numeric band (66 of 175 share the prefix `4202`), which is what you get from
PubMed identifiers assigned in the same indexing window. The linking is picking
up records adjacent in time, not in content.

WHAT IT MEASURES
----------------
Content-word overlap between the news article and each linked paper's title. It
is a deliberately crude test -- a real supporting citation shares vocabulary with
the claim it supports, and a citation sharing NOTHING is not evidence of
anything.

Crude cuts both ways, so the result is reported as a band rather than a verdict:
overlap can miss a genuine supporting paper that uses different words, and can
credit an unrelated one that happens to share a common term.

Requires network (NCBI E-utilities). Verdicts are committed.

Usage:
    python scripts/news_verification_audit.py
"""

import collections
import json
import re
import sys
import time
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import PROJECT_ROOT  # noqa: E402

INDEX = PROJECT_ROOT / "news" / "NEWS_INDEX.jsonl"
OUT = PROJECT_ROOT / "analysis" / "news-verification-audit.md"
RAW = PROJECT_ROOT / "analysis" / "news-verification-audit.json"

# Words too common to count as shared subject matter.
STOP = set(
    "the a an of and or in on for with to by at from as is are was were this that "
    "have has had been be can could may might will would new study studies research "
    "using via into over under more most less than then when what which who how why "
    "its it their they them there here about after before during between within "
    "results result found find shows show showed报".split())


def titles(pmids: list) -> dict:
    out = {}
    for i in range(0, len(pmids), 150):
        batch = pmids[i:i + 150]
        url = ("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
               "?db=pubmed&retmode=json&id=" + ",".join(batch))
        try:
            res = json.load(urllib.request.urlopen(url, timeout=90))["result"]
        except Exception as exc:
            print(f"  ! esummary failed: {exc}", file=sys.stderr)
            continue
        for p in batch:
            if p in res:
                out[p] = res[p].get("title", "")
        time.sleep(0.4)
    return out


def content_words(s: str) -> set:
    return {w for w in re.findall(r"[a-z]{4,}", (s or "").lower()) if w not in STOP}


def main() -> int:
    if not INDEX.exists():
        print(f"missing {INDEX}", file=sys.stderr)
        return 1
    rows = [json.loads(l) for l in INDEX.read_text().splitlines() if l.strip()]
    linked = [r for r in rows if r.get("linked_pmids")]
    pmids = sorted({p for r in linked for p in r["linked_pmids"]})
    print(f"{len(rows)} claims, {len(linked)} with linked PMIDs, "
          f"{len(pmids)} distinct identifiers", flush=True)
    tmap = titles(pmids)

    pairs = []
    for r in linked:
        news = content_words(r.get("article_title", "")) | content_words(r.get("claim_text", ""))
        for p in r["linked_pmids"]:
            t = tmap.get(p)
            if t is None:
                continue
            pairs.append({"pmid": p, "overlap": len(news & content_words(t)),
                          "article": r.get("article_title", "")[:70],
                          "paper": t[:70],
                          "claim_id": r.get("claim_id", "")})
    zero = [x for x in pairs if x["overlap"] == 0]
    weak = [x for x in pairs if x["overlap"] == 1]
    ok = [x for x in pairs if x["overlap"] >= 2]

    prefix = collections.Counter(p[:4] for p in pmids)
    top_prefix, top_n = prefix.most_common(1)[0]

    L = [
        "# Do the news pipeline's \"verified\" PMIDs support the claims? (#NEWS-VERIFY)", "",
        "Generated by `scripts/news_verification_audit.py`.", "",
        f"`news/NEWS_INDEX.jsonl` marks **{len(linked)}** claims `verified` and attaches",
        f"`linked_pmids` as the evidence. Two of those links reached the manuscript as",
        "footnotes reading *\"Verified: PMID:X\"*.", "",
        "## The measurement", "",
        "Content-word overlap between each news article and each linked paper's title.",
        "A real supporting citation shares vocabulary with the claim it supports; one",
        "sharing nothing is not evidence of anything.", "",
        "| overlap with the news article | pairs | share |", "|---|---|---|",
        f"| **none** | {len(zero):,} | **{100*len(zero)/max(1,len(pairs)):.1f}%** |",
        f"| one word | {len(weak):,} | {100*len(weak)/max(1,len(pairs)):.1f}% |",
        f"| two or more | {len(ok):,} | {100*len(ok)/max(1,len(pairs)):.1f}% |",
        f"| total resolved pairs | {len(pairs):,} | |", "",
        "## What went wrong", "",
        f"The linked identifiers cluster in a narrow numeric band -- {top_n} of",
        f"{len(pmids)} share the prefix `{top_prefix}`. PubMed identifiers are assigned",
        "sequentially as records are indexed, so that is the signature of matching on",
        "**when a record was indexed rather than what it says**.", "",
        "The clearest case: a claim about electric fields treating brain cancer, linked",
        "to papers on freshwater fish biodiversity, school-based vision programs,",
        "printable colouration, post-vaccine inflammation tracking, and a survey of",
        "speech-language pathologists.", "",
        "## Examples with no shared content word", "",
        "| news article | linked paper |", "|---|---|",
    ]
    for x in zero[:15]:
        L.append(f"| {x['article']} | {x['paper']} |")

    L += [
        "", "## What this does not say", "",
        "Word overlap is a crude test and it cuts both ways. It can miss a genuine",
        "supporting paper that describes the same finding in different vocabulary, and",
        "it can credit an unrelated paper that happens to share a common term. So the",
        "figure above is a band, not a verdict on any individual claim.", "",
        "What it does establish is that the `verified` label cannot be relied on as it",
        "stands. A verification process whose links are mostly content-unrelated has",
        "not verified anything, whatever the field says.", "",
        "## What should happen", "",
        "* The `verification_status: \"verified\"` label should not be trusted, and",
        "  anything quoting it -- including manuscript footnotes -- should stop asserting",
        "  verification until the linking is rebuilt.",
        "* The linking step needs to match on content. Whatever it does now produces",
        "  index-adjacent records.",
        "* Re-running it is a separate job from this audit, which only measures.", "",
        "## Limits", "",
        "* Titles only. A paper whose abstract supports a claim its title does not",
        "  mention counts here as unrelated, so the no-overlap share is an over-estimate",
        "  of the true error rate.",
        "* Only claims that carry `linked_pmids` are examined; claims with none are",
        "  outside this measurement entirely.",
        "* The stoplist is hand-written, so overlap counts shift slightly with it.",
    ]

    OUT.write_text("\n".join(L) + "\n")
    RAW.write_text(json.dumps({
        "claims_total": len(rows), "claims_with_links": len(linked),
        "distinct_pmids": len(pmids), "pairs_resolved": len(pairs),
        "zero_overlap": len(zero), "one_word": len(weak), "two_plus": len(ok),
        "dominant_prefix": top_prefix, "dominant_prefix_count": top_n,
        "examples_zero_overlap": zero[:40],
    }, indent=2) + "\n")
    print(f"\nno shared content word: {len(zero)}/{len(pairs)} "
          f"({100*len(zero)/max(1,len(pairs)):.1f}%)")
    print(f"wrote {OUT}\nwrote {RAW}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
