#!/usr/bin/env python3
"""The engine's O2 dependence is linear; radiobiology's is a hyperbola (#726)

THE CLAIM THIS WITHDRAWS
------------------------
#726 proposed adding ionizing radiation to the engine and rested on one
sentence: that `oxygen::o2_dependent_exo_factor` "is the oxygen enhancement
ratio under another name", so radiation could enter through machinery that
already exists.

It is not. The engine computes

    f(s) = (1 - d) + d * s                          [linear in O2]

and the Alper-Howard-Flanders OER, the form radiobiology has used since 1956, is

    m(p) = (m_max * p + K) / (p + K)                [saturating hyperbola]

Those are different functions, and the difference is not cosmetic: the hyperbola
rises steeply over the first few mmHg and then flattens, which is the whole
reason the oxygen effect is a THRESHOLD phenomenon in radiotherapy. A linear
factor spreads the same total change evenly across the range.

WHY THAT MATTERS HERE SPECIFICALLY
-----------------------------------
The engine's most contested parameter is the O2 dependence of exogenous ROS --
PREREGISTRATION.md flags P4 as its least certain leg, and §7.1's hypoxia claim
turns on what happens as O2 approaches zero. That is precisely the regime where
the two forms disagree most.

So the correct version of #726's argument is stronger than the one it made: the
engine does not already contain the OER, and adopting the measured functional
form would be a genuine improvement to the parameter the project is least sure
about -- with eighty years of published measurements available as a calibration
target, which the layer-freeze policy requires before any new axis lands.

WHAT THIS SCRIPT DOES
---------------------
Quantifies the disagreement across the physiological range, so the size of the
change is a number rather than an argument. It does NOT modify the engine:
changing a functional form moves every result that depends on it, including
committed byte-identity gates, and that is a separate reviewed act.

Usage:
    python scripts/oxygen_form_check.py
"""

import argparse
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUT_MD = PROJECT_ROOT / "analysis" / "oxygen-form-check.md"
OUT_JSON = PROJECT_ROOT / "analysis" / "oxygen-form-check.json"

# Alper & Howard-Flanders 1956. K is the pO2 at which the modifier is halfway
# between its anoxic and fully-oxic values; reported values cluster near 3 mmHg.
# m_max is the maximum enhancement, near 3 for sparsely ionising radiation.
OER_K_MMHG = 3.0
OER_M_MAX = 3.0
# Physiological range: anoxic core to arterial. Tumour hypoxia is conventionally
# below 10 mmHg, which is where the two forms are compared most carefully.
PO2_POINTS = [0.0, 0.5, 1.0, 2.0, 3.0, 5.0, 7.5, 10.0, 20.0, 40.0, 60.0]
PO2_MAX = 60.0


def engine_linear(o2_supply: float, dependence: float) -> float:
    """The engine's form, reproduced exactly from oxygen.rs."""
    d = min(max(dependence, 0.0), 1.0)
    s = min(max(o2_supply, 0.0), 1.0)
    return min(max(1.0 - d + d * s, 0.0), 1.0)


def oer_hyperbola(po2_mmhg: float) -> float:
    """Alper-Howard-Flanders, normalised to 1.0 at full oxygenation.

    The raw form gives a dose-modifying factor from 1 (anoxic) to m_max (oxic).
    Normalised by m_max it becomes an efficacy factor in (1/m_max, 1], directly
    comparable to the engine's yield factor.
    """
    raw = (OER_M_MAX * po2_mmhg + OER_K_MMHG) / (po2_mmhg + OER_K_MMHG)
    return raw / OER_M_MAX


def compare(dependence: float) -> dict:
    rows = []
    for p in PO2_POINTS:
        s = p / PO2_MAX
        lin = engine_linear(s, dependence)
        hyp = oer_hyperbola(p)
        rows.append({"po2_mmhg": p, "o2_supply": s,
                     "engine_linear": lin, "oer_hyperbola": hyp,
                     "abs_diff": abs(lin - hyp),
                     "ratio": (lin / hyp) if hyp > 0 else None})
    hyp_lo = [r for r in rows if r["po2_mmhg"] <= 10.0]
    return {
        "dependence": dependence,
        "oer_k_mmhg": OER_K_MMHG, "oer_m_max": OER_M_MAX, "po2_max": PO2_MAX,
        "rows": rows,
        "max_abs_diff": max(r["abs_diff"] for r in rows),
        "max_abs_diff_at": max(rows, key=lambda r: r["abs_diff"])["po2_mmhg"],
        "max_abs_diff_hypoxic": max(r["abs_diff"] for r in hyp_lo),
    }


def render(d: dict) -> str:
    L = ["# The engine's oxygen dependence is not the oxygen enhancement ratio", ""]
    L += ["*Generated by `scripts/oxygen_form_check.py`. Every figure is "
          "recomputed.*", ""]

    L += ["#726 proposed adding ionizing radiation through machinery the engine "
          "already has, resting on the claim that "
          "`oxygen::o2_dependent_exo_factor` is the oxygen enhancement ratio "
          "under another name. **It is not.**", ""]
    L += ["```",
          "engine   f(s) = (1 - d) + d * s                    linear in O2",
          f"OER      m(p) = ({OER_M_MAX}*p + {OER_K_MMHG}) / (p + {OER_K_MMHG})"
          "              saturating hyperbola",
          "```", ""]
    L += ["The hyperbola rises steeply over the first few mmHg then flattens, "
          "which is why the oxygen effect is a THRESHOLD phenomenon in "
          "radiotherapy. A linear factor spreads the same total change evenly "
          "across the range.", ""]

    L += [f"## How far apart, at dependence = {d['dependence']}", ""]
    L += ["| pO2 (mmHg) | engine (linear) | OER (hyperbola) | difference |",
          "|--:|--:|--:|--:|"]
    for r in d["rows"]:
        L.append(f"| {r['po2_mmhg']:g} | {r['engine_linear']:.3f} | "
                 f"{r['oer_hyperbola']:.3f} | {r['abs_diff']:.3f} |")
    L += [""]
    L += [f"Maximum disagreement is **{d['max_abs_diff']:.3f}** at "
          f"{d['max_abs_diff_at']:g} mmHg, and **{d['max_abs_diff_hypoxic']:.3f}** "
          f"within the tumour-hypoxic range below 10 mmHg.", ""]

    L += ["## Why this makes #726's case stronger, not weaker", ""]
    L += ["The engine's most contested parameter is exactly this one. "
          "`PREREGISTRATION.md` flags P4 -- the SDT-under-hypoxia leg -- as its "
          "least certain, and §7.1's claim turns on behaviour as O2 approaches "
          "zero. That is the regime where the two forms disagree most.", ""]
    L += ["So the honest version of the proposal is better than the one it "
          "made: the engine does **not** already contain the OER, and adopting "
          "the measured functional form would improve the parameter the project "
          "is least sure about -- with eighty years of published measurements "
          "as a calibration target, which the layer-freeze policy requires "
          "before any new axis lands.", ""]

    L += ["## What this does not do", ""]
    L += ["* It does not change the engine. Changing a functional form moves "
          "every result that depends on it, including the committed "
          "byte-identity gates, and that is a separate reviewed act.",
          "* It does not calibrate anything. `K` and `m_max` here are the "
          "canonical Alper-Howard-Flanders values, not a fit to this model.",
          "* The pO2-to-`o2_supply` mapping is linear over a 0-60 mmHg range, "
          "which is an assumption this comparison makes and the engine does not "
          "state. A different mapping changes the size of the gap but not the "
          "shape difference, which is the finding.",
          ""]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dependence", type=float, default=1.0)
    ap.add_argument("--render-only", action="store_true")
    args = ap.parse_args()
    if args.render_only:
        d = json.loads(OUT_JSON.read_text())
    else:
        d = compare(args.dependence)
        if d["max_abs_diff"] == 0.0:
            raise SystemExit(
                "the two forms agree everywhere, which is not a finding -- it "
                "is what a bug in one of them looks like.")
        OUT_JSON.write_text(json.dumps(d, indent=1, sort_keys=True) + "\n",
                            encoding="utf-8")
    OUT_MD.write_text(render(d), encoding="utf-8")
    print(f"wrote {OUT_MD}")
    print(f"wrote {OUT_JSON}")
    print(f"  max |diff| {d['max_abs_diff']:.3f} at {d['max_abs_diff_at']:g} mmHg; "
          f"hypoxic-range max {d['max_abs_diff_hypoxic']:.3f}")


if __name__ == "__main__":
    main()
