#!/usr/bin/env python3
"""An optimum that falls out of somebody else's measurement.

WHAT IS BEING CHECKED
---------------------
An antibody-drug conjugate has one obvious design knob -- how much drug to put
on each antibody -- and the obvious answer is wrong. More payload per antibody
means more drug delivered by each one that arrives, and fewer arriving, because
a heavily conjugated antibody is cleared faster.

Hamblett 2004 (PMID 15501986) measured the second half on one conjugate at
three loadings: DAR 8 clears three times faster than DAR 4 and five times
faster than DAR 2. Those ratios are the input. The optimum is the output, and
it is not chosen here.

THE PART THAT IS A FINDING ABOUT THE DATA
-----------------------------------------
A single power law in DAR cannot pass through both measured ratios. Fitted to
`c(8)/c(2) = 5` it predicts `c(8)/c(4) = 2.24` against a measured 3. The two
ratios together say the clearance penalty ACCELERATES -- slower than linear
between 2 and 4, faster between 4 and 8 -- and that acceleration is exactly
what produces an interior optimum. A smoother curve would have removed the
result, which is the sort of thing a fit chosen for tidiness does.

AND THE IN-VITRO/IN-VIVO DISAGREEMENT
-------------------------------------
The same paper reports the in-vitro potency ordering as E8 < E4 < E2 by IC50 --
the most heavily loaded conjugate is the most potent in a dish, where nothing
is cleared -- while in vivo E4 matched E8 at equal antibody dose. Same
molecules, opposite ordering. This book argues about the in-vitro-to-in-vivo
gap in almost every chapter; here is a case where the field measured both
halves of it in one experiment.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RUST = REPO / "simulations" / "ferroptosis-core" / "src" / "adc.rs"
DATA = REPO / "analysis" / "calibration" / "adc_drug_loading.csv"
OUT_MD = REPO / "analysis" / "calibration" / "adc-validation.md"
OUT_JSON = REPO / "analysis" / "calibration" / "adc-validation.json"


def rust_points() -> list:
    """The anchor points, parsed from the crate rather than restated."""
    src = RUST.read_text()
    m = re.search(r"pub const HAMBLETT_DAR_POINTS: \[\(f64, f64\); 3\] = \[(.*?)\];",
                  src, re.S)
    if not m:
        raise SystemExit("ERROR: HAMBLETT_DAR_POINTS not found in adc.rs")
    out = []
    for dar, expr in re.findall(r"\(([0-9.]+), ([^)]+)\)", m.group(1)):
        out.append((float(dar), eval(expr, {"__builtins__": {}}, {})))
    return out


def clearance(dar, points):
    lo, hi = (points[0], points[1]) if dar <= points[1][0] else (points[1], points[2])
    exponent = math.log(hi[1] / lo[1]) / math.log(hi[0] / lo[0])
    return lo[1] * (dar / lo[0]) ** exponent


def scan() -> dict:
    points = rust_points()
    with DATA.open() as fh:
        measured = list(csv.DictReader(l for l in fh if not l.startswith("#")))

    # The single-power-law alternative, kept because its failure is the finding.
    single_exponent = math.log(5.0) / math.log(4.0)
    single_c8_over_c4 = (8.0 / 2.0) ** single_exponent / (4.0 / 2.0) ** single_exponent

    curve = []
    d = 1.0
    best = (0.0, -1.0)
    while d <= 12.001:
        c = clearance(d, points)
        delivered = d / c
        curve.append({"dar": round(d, 2), "clearance": round(c, 4),
                      "delivered_per_dose": round(delivered, 4),
                      "in_vitro_potency": round(d / 2.0, 3)})
        if delivered > best[1]:
            best = (round(d, 2), delivered)
        d += 0.25

    return {
        "anchor_points": [{"dar": p[0], "clearance_relative_to_dar2": round(p[1], 4)}
                          for p in points],
        "measured_rows": measured,
        "single_power_law_predicts_c8_over_c4": round(single_c8_over_c4, 3),
        "measured_c8_over_c4": 3.0,
        "curve": curve,
        "optimal_dar": best[0],
        "delivered_at_optimum": round(best[1], 4),
        "delivered_8_over_4": round((8.0 / clearance(8.0, points))
                                    / (4.0 / clearance(4.0, points)), 4),
    }


def assemble(raw: dict) -> dict:
    raw["verdict"] = {
        "optimum_is_emergent": "YES -- both factors monotonic, the ratio is not",
        "optimum_dar": raw["optimal_dar"],
        "single_power_law_fits_both_ratios":
            "NO" if abs(raw["single_power_law_predicts_c8_over_c4"]
                        - raw["measured_c8_over_c4"]) > 0.1 else "YES",
        "in_vitro_and_in_vivo_orderings_agree": "NO",
    }
    return raw


def render(d: dict) -> str:
    L = ["# The drug-antibody ratio, and an optimum nobody chose", "",
         "*Generated by `scripts/validate_adc.py --render-only`. Pure stdlib; "
         "runs offline in CI. The anchor points are parsed from "
         "`simulations/ferroptosis-core/src/adc.rs`.*", "",
         "## The measurement", "",
         "Hamblett 2004 (PMID 15501986) conjugated one antibody at three drug "
         "loadings and measured how fast each cleared:", "",
         "| conjugate | DAR | clearance, relative to DAR 2 | in-vitro potency rank |",
         "|---|--:|--:|--:|"]
    for row in d["measured_rows"]:
        L.append(f"| {row['conjugate']} | {row['drug_antibody_ratio']} | "
                 f"{row['clearance_relative_to_dar2']} | "
                 f"{row['in_vitro_potency_rank']} (1 = most potent) |")
    L += ["",
          "## A single power law cannot fit both ratios, and that is the finding",
          "",
          f"Fitted to `c(8)/c(2) = 5`, a power law predicts "
          f"`c(8)/c(4) = {d['single_power_law_predicts_c8_over_c4']}` against a "
          f"measured {d['measured_c8_over_c4']:.0f}. The two ratios together "
          "say the penalty ACCELERATES: clearance rises more slowly than "
          "linearly between DAR 2 and 4, and faster than linearly between 4 "
          "and 8.", "",
          "**That acceleration is what produces an interior optimum.** A "
          "smoother curve chosen for tidiness would have removed the result "
          "before it appeared.", "",
          "## The optimum", "",
          f"Delivered payload per unit antibody dose is `DAR / clearance(DAR)`. "
          f"Both factors are monotonic; the ratio is not, and it peaks at "
          f"**DAR {d['optimal_dar']:g}** -- which is where the field settled "
          f"for this payload class, and which nothing here was tuned to "
          f"produce.", "",
          f"The consequence the paper reports independently: a DAR-8 conjugate "
          f"delivers {d['delivered_8_over_4']:.2f} times what a DAR-4 one does "
          "at equal antibody dose, despite carrying twice the drug. Hamblett "
          "found their in-vivo activity comparable.", "",
          "## The in-vitro and in-vivo orderings disagree", "",
          "In a dish nothing is cleared, so potency rises monotonically with "
          "loading and the eight-loaded conjugate is the most potent. In an "
          "animal the four-loaded one matches it at equal antibody dose. Same "
          "molecules, opposite ordering, measured in one study -- which is the "
          "in-vitro-to-in-vivo gap this book argues about elsewhere, with both "
          "halves present.", "",
          "## What this does not establish", "",
          "- **The interpolation is an assumption.** Two ratios do not "
          "determine a curve; log-linear WITHIN each measured segment is the "
          "simplest form passing through both, and outside DAR 2 to 8 nothing "
          "is measured and the extrapolation should not be trusted.",
          "- **One conjugate, one payload, one antibody.** The optimum is not "
          "a general property of ADCs. Newer conjugates with different linkers "
          "and payloads are deliberately built at higher loading, which this "
          "single-study anchor cannot speak to.",
          "- **Delivered payload is not efficacy.** The model converts neither "
          "to a kill fraction nor to a response, and the binding-site barrier "
          "that sits beside it is uncalibrated -- direction only.", ""]
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--render-only", action="store_true")
    a = ap.parse_args()
    d = assemble(json.loads(OUT_JSON.read_text()) if a.render_only else scan())
    OUT_JSON.write_text(json.dumps(d, indent=1) + "\n")
    OUT_MD.write_text(render(d))
    print(f"wrote {OUT_MD}")
    print(f"wrote {OUT_JSON}")
    print(f"  optimum at DAR {d['optimal_dar']}, delivered(8)/delivered(4) = "
          f"{d['delivered_8_over_4']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
